Wed, 09 Nov 2016 11:17:07:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:34:35:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:34:36:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : %d format: a number is required, not str issue!
Wed, 09 Nov 2016 11:35:19:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25298502 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:35:19:insert_logs.py[line:24] INFO insert_tickets_effort-->Insert tickets to mysql  25443496 : unsupported format character ')' (0x29) at index 47 issue!
Wed, 09 Nov 2016 11:36:09:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:44:06:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:44:49:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:46:54:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:47:10:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 09 Nov 2016 11:47:10:insert_logs.py[line:24] INFO Run done!
Wed, 09 Nov 2016 11:48:51:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:49:02:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 09 Nov 2016 11:49:02:insert_logs.py[line:24] INFO Run done!
Wed, 09 Nov 2016 11:49:18:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 11:49:31:MS_DB_query.py[line:103] INFO Start Query Db.....
Wed, 09 Nov 2016 11:49:32:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets Done!
Wed, 09 Nov 2016 11:49:33:insert_logs.py[line:24] INFO Db  get_icm_azure_info Done!
Wed, 09 Nov 2016 11:49:33:insert_logs.py[line:35] INFO (25298502L, 3, u'WA-IaaS|Sev 3 | The VM failed to start(SR_2016103156577)', u'635', u'Incident', u'4. Completed Investigation', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 31, 11, 16, 49, 80000), datetime.datetime(2016, 11, 1, 8, 34, 9), datetime.datetime(2016, 11, 1, 9, 5, 42), u'RESOLVED', None, u'Azure Hardware Datacenter Manager - China', u'AZUREHARDWAREDATACENTERMANAGERCHINA\\DatacenterPlatform-LowPri', u'RDOS - China', u'RDOSCHINA\\AzureHost-Sev-3-4', u'WASU', u'RDOS - China', u'', u"he VM(A7) can't start on the on the 2016/10/30 (UTC). We escalated to RDos team. -->\xa0\xa0Francis David ask WALS to OFR the node --> transfer to DCM-> vm bjtdxhq12 scaled up to A7, nothing we can do here, so we resolved.")
Wed, 09 Nov 2016 11:49:33:insert_logs.py[line:35] INFO (25443496L, 4, u'[POD VMA] | Sev 4 | [MS-LED]Pls to investigation VM Restart Cause (SR_2016110257151)', u'380', u'Root Cause', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 3, 10, 58, 34, 667000), datetime.datetime(2016, 11, 4, 7, 41, 58), datetime.datetime(2016, 11, 4, 7, 43, 9), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'RDOS - China', u'RDOSCHINA\\AzureHost-Sev-3-4', u'Operating System', u'RDOS - China', u'', u"vm reboot --> RCA request : error 00001520] IVM::Update failed with 0x80070bc2, returning generic VMAL error 0x80070bc2, it's the same vm in ICM 24550739\nPG confirmed it's bug.-->This ticket is from the same customer and the same VM in one week, we need to follwo up in the mail thread")
Wed, 09 Nov 2016 11:49:33:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 09 Nov 2016 11:49:33:insert_logs.py[line:24] INFO Run done!
Wed, 09 Nov 2016 13:00:20:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 13:00:51:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 09 Nov 2016 13:00:51:insert_logs.py[line:24] INFO Run done!
Wed, 09 Nov 2016 13:01:28:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 13:01:56:MS_DB_query.py[line:57] INFO Start Query Db.....
Wed, 09 Nov 2016 13:01:56:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets Done!
Wed, 09 Nov 2016 13:01:56:insert_logs.py[line:24] INFO get_icm_efforttime  function issue : Connection is closed.  
Wed, 09 Nov 2016 13:01:56:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 09 Nov 2016 13:01:56:insert_logs.py[line:24] INFO Run done!
Wed, 09 Nov 2016 13:06:34:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Wed, 09 Nov 2016 13:07:03:MS_DB_query.py[line:57] INFO Start Query Db.....
Wed, 09 Nov 2016 13:07:03:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets Done!
Wed, 09 Nov 2016 13:07:04:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 09 Nov 2016 13:07:04:insert_logs.py[line:24] INFO Run done!
Wed, 09 Nov 2016 13:12:36:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Fri, 11 Nov 2016 13:25:45:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Fri, 11 Nov 2016 13:26:15:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Fri, 11 Nov 2016 13:26:54:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Fri, 11 Nov 2016 13:37:46:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Fri, 11 Nov 2016 13:39:56:MS_DB_query.py[line:36] INFO Connect Warwhouse OK!
Tue, 15 Nov 2016 01:21:00:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Tue, 15 Nov 2016 01:21:01:MS_DB_query.py[line:158] INFO Start Query Db.....
Tue, 15 Nov 2016 01:21:02:MS_DB_query.py[line:193] INFO get_wasu_icm_tickets_user  function issue : (102, "Incorrect syntax near 'a'.DB-Lib error message 20018, severity 15:\nGeneral SQL Server error: Check messages from the SQL Server\n")  
Tue, 15 Nov 2016 01:21:53:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Tue, 15 Nov 2016 01:21:53:MS_DB_query.py[line:158] INFO Start Query Db.....
Tue, 15 Nov 2016 01:21:54:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Tue, 15 Nov 2016 01:34:39:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Tue, 15 Nov 2016 01:38:04:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Tue, 15 Nov 2016 01:38:47:MS_DB_query.py[line:158] INFO Start Query Db.....
Tue, 15 Nov 2016 01:38:49:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:24] INFO Db  get_icm_azure_info Done!
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (23894895L, 4, u'VPN Daily Scan Support \u2013 October 2016', u'2100', '', '', u'Diagnostics Data Collection', 'other', '', datetime.datetime(2016, 10, 1, 18, 52, 4, 417000), datetime.datetime(2016, 11, 5, 17, 5, 46), datetime.datetime(2016, 11, 5, 17, 6, 3, 420000), u'RESOLVED', u'Blocked', u'Windows Azure Operations Center - China', u'Support', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'update 11/04 effort.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (23925785L, 4, u'check the usage data of subscription id for ExpressRoute on 8/31/2016', u'220', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 2, 17, 32, 21, 240000), datetime.datetime(2016, 10, 5, 23, 59, 56), datetime.datetime(2016, 10, 6, 0, 0, 5, 657000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', '', u'EXPRESSROUTE', u'Cloudnet - China', u'', u'check the ER bytes in and bytes out-->Finish checking, resolve this one')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (23932137L, 4, u'WATS |  Sev 4|[MS-LED] RCA for VM "xw-xtionweb01" reboot (SR_2016092952980)', u'90', u'Incident', '', u'User Issue', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 2, 21, 6, 21, 233000), datetime.datetime(2016, 10, 2, 22, 52, 57), datetime.datetime(2016, 10, 2, 22, 53, 20), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'RDFE - China', u'CRI,Activation', u'VM inside process request VM shutdown')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (23934202L, 4, u'WATS | Sev 4 |[MS-LED] RCA for VM "pd1" and "pd2" cannot connect(SR_2016092952926)', u'140', u'Incident', '', u'User Issue', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 2, 22, 13, 47, 950000), datetime.datetime(2016, 10, 2, 22, 51, 21), datetime.datetime(2016, 10, 2, 22, 51, 59, 930000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'RDFE - China', u'CRI,Activation', u'During the issue time, VMs cpu upto 100%')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24073399L, 4, u'Please help check the Subscripton ID and Deployment ID of :42.159.6.7', u'30', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 4, 19, 23, 54, 210000), datetime.datetime(2016, 10, 4, 20, 18, 25), datetime.datetime(2016, 10, 4, 20, 18, 36, 627000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASU', u'Windows Azure Operations Center - China', u'', u'check done')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24125758L, 4, u'WA-IaaS|SR_2016100553269_\u2009[HMC]Unable to connect the VM RCA', u'60', u'Root Cause', '', u'User Issue', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 5, 16, 32, 30, 460000), datetime.datetime(2016, 10, 8, 19, 33, 23), datetime.datetime(2016, 10, 8, 19, 33, 37, 83000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'RDFE - China', u'CRI', u'We find no error about node but the VM CPU is very high from 15:10 to 15:30. Customer reboot VM at 15:30:38 manually.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24133845L, 3, u'Sev 3 | WATS | SR_2016071343104_VMSS can not Scale up [podplat] (prior 20380592)', u'400', u'Availability', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 5, 21, 36, 49, 687000), datetime.datetime(2016, 10, 5, 21, 41, 43), datetime.datetime(2016, 10, 5, 21, 42, 13), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Azure Insights - China', u'AZUREINSIGHTSCHINA\\InsightsBackend', '', u'Windows Azure Operations Center - China', u'', u'this issue has been fixed.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24169768L, 3, u'WATS| Sev 3 | [MS-LED]VM can not be accessed (SR_2016100653279)', u'185', '', '', u'User Issue', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 6, 14, 12, 40, 930000), datetime.datetime(2016, 10, 8, 18, 58, 21), datetime.datetime(2016, 10, 8, 18, 58, 39), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'WASU', u'Windows Azure Operations Center - China', u'', u'CPU too high, looks VM inside issue.--> the vm back to normal')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24171655L, 3, u'HTTPS request from PAAS to US IP failed, packet drop (MSSolve: 116100514761585)', u'300', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 6, 15, 14, 29, 883000), datetime.datetime(2016, 10, 11, 9, 21, 48), datetime.datetime(2016, 10, 11, 9, 22, 9, 903000), u'RESOLVED', u'Blocked', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Physical Network', u'Windows Azure Operations Center - China', u'packet drop', u'diagnosed to be occasional network congestion from ISP network')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24179204L, 3, u'Network | Brooklyn | VPN Gateway Issue (SR_2016100153224)', u'1250', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 6, 19, 31, 9, 817000), datetime.datetime(2016, 10, 8, 16, 8, 8), datetime.datetime(2016, 10, 8, 22, 24, 38, 940000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u'after the customer reset Azure Gateway, the VPN channel has established successfully., the customer reset the gateway and\xa0 set the share key to the same')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24180012L, 3, u'VPN disconnected issue CTT 1610060098117100 (SR_2016100653284) (SR_2016100653287)', u'45', u'Incident', '', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 6, 19, 55, 53, 767000), datetime.datetime(2016, 10, 6, 19, 56, 32), datetime.datetime(2016, 10, 6, 19, 57, 25), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'NW/IM', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'', u'CT network issue.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24236391L, 3, u'Network | Brooklyn | VPN Gateway Issue (SR_2016100653281\u2009_\u2009[MS-LED]VPN connectivity issue)', u'90', u'Incident', '', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 7, 19, 42, 48, 760000), datetime.datetime(2016, 10, 8, 16, 14, 7), datetime.datetime(2016, 10, 8, 16, 17, 5, 817000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Windows Azure Operations Center - China', u'VPN Gateway', u'Need customer provide tracroute . it is the same to case |IcM24285865|Networking | Virtual Networking | VPN packet drop (SR_2016100653281')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24242986L, 3, u'Network | Brooklyn | VPN Gateway Issue (SR_2016100153224) failed to get the diagnostics log using the acis', u'600', u'Incident', u'2. Engaged', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 7, 23, 39, 27, 763000), datetime.datetime(2016, 10, 12, 2, 11, 52), datetime.datetime(2016, 10, 12, 5, 16, 37), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u"Our test sub no issue, But customer sub have issue. Try to diagnose customer's GW, no result.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24284728L, 4, u'Transfer To New Subscription per customer (Asiainfo Security) request', u'650', '', '', u'Update Subscription Setting', 'Component', u'Component Team', datetime.datetime(2016, 10, 8, 11, 0, 33, 990000), datetime.datetime(2016, 10, 13, 12, 30, 47), datetime.datetime(2016, 10, 13, 12, 31, 2, 247000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'Azure subscription ID: \u201c5f62bed9-511e-44c7-bba4-2a0cb4d0e860\u201d was deleted, and there is no any possibility to access it (from MSFT support team\u2019s feedback). I had a mail to Xiaodong and Chi before, and asked them to setup VM extension publisher permission to the new subscription ID (see below info, and we could change the name to AsiaInfo). If we could not replace my previous subscription ID (5f62bed9-511e-44c7-bba4-2a0cb4d0e860) with this new one, we could re-publish a new VM extension and ask MSFT to remove the current VM extension.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24285865L, 3, u'Networking | Virtual Networking | VPN packet drop (SR_2016100653281)', u'120', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 8, 11, 39, 27, 193000), datetime.datetime(2016, 10, 9, 14, 53, 54), datetime.datetime(2016, 10, 9, 14, 54, 30, 37000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'packet drop', u'oversea ISP network issue')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24288024L, 4, u'[Mooncake]| Redis Cache| the reason for connot create redis', u'450', u'Root Cause', u'4. Completed Investigation', u'Platform Change', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 8, 13, 5, 51, 643000), datetime.datetime(2016, 10, 11, 4, 28, 37), datetime.datetime(2016, 10, 11, 4, 28, 58), u'RESOLVED', u'Investigate', u'Redis Cache - China', u'WINDOWSAZURECACHECHINA\\Triage', u'Redis Cache - China', u'WINDOWSAZURECACHECHINA\\Triage', u'REDIS Managed Cache Service', u'Redis Cache - China', u'CRI,AzureCache', u'RCA link:https://icm.ad.msft.net/imp/IncidentReportDetails2.aspx?pirReportId=44791\nThe issue surfaced as a result of an update and we update each region at different times, causing the time mismatch.We did update China North at the customer issue time and from our records, we saw that the customer ran into the same issue as the one in the RCA.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24290456L, 4, u'Networking | Virtual Networking | alerts indicated the inner disconnection of VMs during 4:20PM-4:22PM of Sep. 30th (SR_2016093053120)', u'420', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 8, 14, 31, 12, 543000), datetime.datetime(2016, 10, 11, 12, 13, 14), datetime.datetime(2016, 10, 11, 12, 14, 38), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u'', u'advice customer to diagnose from internal log')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24291790L, 4, u'check info', u'50', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 8, 15, 10, 13, 810000), datetime.datetime(2016, 10, 8, 17, 40, 51), datetime.datetime(2016, 10, 8, 17, 41, 4, 637000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'check info', u'done')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24292266L, 4, u'Please help to get MC sub info', u'90', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 8, 15, 25, 14, 363000), datetime.datetime(2016, 10, 8, 16, 4, 23), datetime.datetime(2016, 10, 8, 16, 5, 11), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'the commands can not be performed even if applied RDFE privilege via JIT.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24295414L, 4, u'WASMS | <SR_2016100653288 Please help to check when the sub became  warned or disable>', u'60', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 8, 16, 51, 40, 347000), datetime.datetime(2016, 10, 8, 17, 42, 45), datetime.datetime(2016, 10, 8, 17, 42, 55, 150000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'LastModified:10/5/2016 12:23:36 AM\n\xa0\xa0\xa0\xa0\xa0\xa0\xa0 SubscriptionStatus:Disabled')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24322244L, 4, u'[Mooncake] WA-PaaS| WorkerRole login display needs to be activated ', u'230', u'Incident', '', u'ByDesign', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 9, 9, 46, 7, 97000), datetime.datetime(2016, 10, 11, 15, 8, 16), datetime.datetime(2016, 10, 11, 15, 8, 27), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', u'AZURERTCHINA\\PaaS/Storage', u'PaaS', u'Windows Azure Operations Center - China', u'', u'issue was gone')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24323664L, 4, u'WASMS | Please help to investigate the reasons for one day delay of the sub to be stopped (SR_2016100653288)', u'220', u'Incident', u'1. Contacted', u'ByDesign', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 9, 10, 42, 25, 787000), datetime.datetime(2016, 10, 11, 1, 59, 22), datetime.datetime(2016, 10, 11, 1, 59, 38), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'RDFE - China', u'AZURERTCHINA\\Infra/Billing', u'RDFE - Infra and Billing', u'RDFE - China', u'', u'Escalate to RDFE-Billing team-->The Usage bill will delay one day to show up and change the state, it is by design')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24324080L, 4, u'WASMS | <SR_2016100953529_No VM (ibiza)  Usage in usage report>', u'210', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 9, 11, 2, 33, 503000), datetime.datetime(2016, 10, 10, 10, 11, 30), datetime.datetime(2016, 10, 10, 10, 11, 56), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u't\u2019s very clear that we can see the ARM \xa0vm lisatest1 and test0928 in the usage report.\nARM vm no deployment id, just have tenant id, the customer can\u2019t see the tenant id on Ibiza portal.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24324441L, 3, u'Can not deploy a cloud service which is on tenant SHA-3', u'140', '', '', '', 'other', '', datetime.datetime(2016, 10, 9, 11, 18, 49, 523000), datetime.datetime(2016, 10, 9, 14, 53, 38), datetime.datetime(2016, 10, 9, 14, 55, 20), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WALS', u'MySQL Database on Azure - China', '', '', u'Windows Azure Operations Center - China', u'', '')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24327595L, 3, u"WATS | IcM 24327595| Sev 3 | [microsoft] In ARM mode of Public IP page's domain name can't be parsed(SR_2016100753314)", u'420', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 9, 13, 25, 39, 623000), datetime.datetime(2016, 10, 12, 1, 39, 50), datetime.datetime(2016, 10, 12, 1, 40, 42), u'RESOLVED', None, u'Azure IaaS Experiences (Ibiza) - China', u'AZUREIAASEXPERIENCESIBIZACHINA\\Triage', u'Cloudnet - China', u'CLOUDNETCHINA\\DNS', u'DNS', u'Cloudnet - China', u'', u'This issue has been fixed by Cloudnet.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24329028L, 4, u'WATS | Networking | ExpressRoute | Sev 4 |  ExpressRoute (SR_2016092652321)', u'20', u'Incident', '', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 9, 14, 22, 50, 887000), datetime.datetime(2016, 10, 9, 19, 24, 5), datetime.datetime(2016, 10, 9, 19, 24, 30, 777000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'EXPRESSROUTE', u'Cloudnet - China', u'Express Route', '')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24330749L, 3, u'WASMS | <Unable to display the balance in manage portal>', u'570', u'Incident', u'4. Completed Investigation', u'ByDesign', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 9, 15, 33, 7, 330000), datetime.datetime(2016, 10, 17, 9, 3, 58), datetime.datetime(2016, 10, 17, 9, 6, 2, 617000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-Experiences', u'WASU', u'AAD Customer Acquisition and Billing - China', u'', u"the management portal that the customer is using has been deprecated\xa0it cannot debug as set no\xa0billing api,\xa0Try the new portal, that's the only feasible solution.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24341285L, 3, u'Can not deploy a cloud service which is on tenant SHA-3', u'330', u'Incident', '', u'Diagnostics Data Collection', 'other', u'First  Party \u2013 MSIT', datetime.datetime(2016, 10, 9, 23, 18, 17, 740000), datetime.datetime(2016, 10, 10, 19, 33, 3), datetime.datetime(2016, 10, 10, 19, 33, 19), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'BJBPrdApp07/13 / SH3PrdApp02 can create DS vm, SH3PrdApp06 can create DSv2 vm')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24360178L, 3, u'Networking | Virtual Networking | ISP link check (SR_2016101053679_[MS-LED]Guangzhou Mobile 4G access Azure is unnormal)', u'150', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 10, 10, 9, 33, 447000), datetime.datetime(2016, 10, 11, 8, 42, 42), datetime.datetime(2016, 10, 11, 8, 43, 9), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'ISP link', u'all good from Azure network,\xa0external ISP issue, need customer to engage local ISP for further look.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24362612L, 4, u'[VMA] WA-IaaS | Unexpected restart_SR_2016101053668', u'290', u'Root Cause', '', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 10, 11, 56, 4, 920000), datetime.datetime(2016, 10, 11, 11, 59, 12), datetime.datetime(2016, 10, 11, 11, 59, 27), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'CRI', u'hardware issue, single instance, gave RCA.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24364330L, 4, u'sub which is deleted could not recharge, but customer can recharge for 1000 RMB', u'1100', '', u'4. Completed Investigation', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 10, 13, 4, 24, 243000), datetime.datetime(2016, 10, 17, 9, 10, 38), datetime.datetime(2016, 10, 17, 9, 11, 11), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\AzureBusinessOperations', u'WASU', u'AAD Customer Acquisition and Billing - China', u'do not receive 1000RMB refund', u"wait for customer's screenshot.-->Escalate to Billing portal team->Tier2 - Experiences-->It should be Commerce team issue")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24369237L, 4, u'Do we have any planed schedule or other workaround to fix the SNAT ports overload issue', u'300', '', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 10, 16, 48, 46, 467000), datetime.datetime(2016, 10, 11, 5, 58, 6), datetime.datetime(2016, 10, 11, 6, 1, 23), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'AutoPilot SLB', u'Cloudnet - China', u'', u"SLB 11.15 is rolling out Static Snat feature which will help alleviate the SNAT port overload issue. If any customers are in urgent need, we can try apply it on these customer's deployments selectively even today. We have a TSG #5700189 for this purpose.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24377069L, 2, u'[Mooncake][21V] - [HDInsight][Azul_SR_2016100753325][MSSolve_SR_116101014777668][HBase cluster regionserver service restarted frequently]', u'615', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 10, 22, 16, 45, 173000), datetime.datetime(2016, 10, 11, 0, 51, 57), datetime.datetime(2016, 10, 19, 13, 33, 7), u'RESOLVED', '', u'HDInsight - China', u'HDINSIGHTCHINA\\LivesiteOnCalls', u'HDInsight - China', u'HDINSIGHTCHINA\\HBase', '', u'HDInsight - China', u'', u'provided solution and waiting for customer feedback.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24377697L, 3, u"MoonCake | WebSites | Can't delete newly created app service plan in new  portal (SR_2016101053819)", u'400', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-WebApp', datetime.datetime(2016, 10, 10, 22, 44, 29, 167000), datetime.datetime(2016, 10, 12, 7, 24, 2), datetime.datetime(2016, 10, 12, 7, 24, 28), u'RESOLVED', None, u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'WebSites', u'App Service (Web Apps) - China', u'', u'Have escalated to PG for help.\nTravis is working on this. Navy has updated mooncake manifest. This issue is mitigated.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24401005L, 4, u'check IP 42.159.145.75', u'40', '', '', u'Diagnostics Data Collection', 'other', '', datetime.datetime(2016, 10, 11, 9, 28, 3, 927000), datetime.datetime(2016, 10, 11, 10, 4, 14), datetime.datetime(2016, 10, 11, 10, 4, 32, 283000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'CC', u'Windows Azure Operations Center - China', u'', u'done with the request.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24401415L, 4, u'WASMS | <SR_2016100953630_Please help to check if the Data transfer usage is match with Usage report >', u'75', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 11, 9, 39, 0, 187000), datetime.datetime(2016, 10, 11, 11, 1, 40), datetime.datetime(2016, 10, 11, 11, 1, 49, 517000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'Check the backend, and the usage is match to the bill')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24403659L, 4, u'check subs & sitenames', u'110', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 11, 10, 56, 0, 520000), datetime.datetime(2016, 10, 11, 14, 23, 44), datetime.datetime(2016, 10, 11, 14, 23, 56, 217000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\CC', u'CC', u'Windows Azure Operations Center - China', u'check subs & sitenames', u'finished check')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24407571L, 4, u'[Mooncake][21V] - [Azul_SR_2016101153880][No MSSolve Case][help to cancel exporting database request]', u'199', u'Incident', '', u'Human Error', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 11, 13, 34, 31, 337000), datetime.datetime(2016, 10, 12, 8, 12, 29), datetime.datetime(2016, 10, 12, 8, 13, 52), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Azure SQL DB - China', '', '', u'Windows Azure Operations Center - China', u'', u'He was migrating his db from asm to arm model)')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24407633L, 4, u'IcM request|HMC P&G| Worker role got  guestheupgrade ', u'700', u'Root Cause', u'4. Completed Investigation', u'User Issue', 'CSS', u'CSS-Shanghai', datetime.datetime(2016, 10, 11, 13, 37, 7, 47000), datetime.datetime(2016, 10, 17, 9, 57, 51), datetime.datetime(2016, 10, 17, 9, 58, 38), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'RDFE - China', u'AZURERTCHINA\\PaaS/Storage', u'PaaS', u'RDFE - China', u'', u'issue diagnosed to be Azure java tool issue,\xa0discuss with Pod TA, who is working on further debugging. agree to resolve')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24411044L, 3, u'Networking | Virtual Networking | [MS-LED]Outbound packet loss to 150.242.59.50:80(SR_2016092051461)', u'900', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 11, 15, 34, 30, 200000), datetime.datetime(2016, 10, 19, 8, 45, 26), datetime.datetime(2016, 10, 19, 20, 10, 3), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u'packet drop', u"PG's had confirm the Pip will fixed customer issue.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24413596L, 4, u'MoonCake | WebSites | <failed to migrate a web app to a new service plan through new portal and PowerShell Tool>', u'150', u'Incident', '', u'User Issue', 'CIE', u'CSS-WebApp', datetime.datetime(2016, 10, 11, 16, 46, 12, 17000), datetime.datetime(2016, 10, 12, 14, 17, 30), datetime.datetime(2016, 10, 12, 14, 18, 9), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'WebSites', u'App Service (Web Apps) - China', u'', u'cannot repro,\xa0test subscription agree to close')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24413803L, 4, u'WATS | Networking | S2S VPN |  Loss Package for S2S VPN (SR_2016101153905)', u'70', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 11, 16, 52, 57, 593000), datetime.datetime(2016, 10, 11, 20, 2, 7), datetime.datetime(2016, 10, 11, 20, 2, 23, 480000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet', u'VPN Gateway', u'Finish capture on Role Instance, and send the package to WATS.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24415446L, 3, u"MoonCake | WebSites | <Ibiza portal can't identify site name repetition  > (SR_2016101053819)", u'300', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-WebApp', datetime.datetime(2016, 10, 11, 17, 44, 47, 610000), datetime.datetime(2016, 10, 12, 4, 0, 2), datetime.datetime(2016, 10, 12, 4, 1, 40), u'RESOLVED', None, u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'WebSites', u'App Service (Web Apps) - China', u'', u'Escalate to Antraes team-->Travis will take a look\nTravis will have a hoxfix.\nBug had been fixed.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24441113L, 3, u'[Mooncake] WA-PaaS| Role in staging slot  stuck in busy for hours ', u'100', u'Incident', '', u'Human Error', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 12, 7, 0, 13, 170000), datetime.datetime(2016, 10, 13, 9, 42, 34), datetime.datetime(2016, 10, 13, 9, 42, 47), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', u'COMPUTEMANAGERMOONCAKE\\ContainerManager', '', u'Windows Azure Operations Center - China', u'', u'You can resolve this ticket as we have found this issue is caused by client code.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24450065L, 3, u'Networking | Virtual Networking | Load Balancer is not working for one VM(SR_2016101254030)', u'320', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 11, 27, 21, 590000), datetime.datetime(2016, 10, 17, 18, 59, 52), datetime.datetime(2016, 10, 17, 19, 0, 30, 193000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'AutoPilot SLB', u'Windows Azure Operations Center - China', u'packet drop', u"load balancer working fine, didn't find any error.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24451770L, 3, u'Networking | Virtural Networking | ICM XXXX | Sev 3 | Source discribution mode SLB distribute request from the same source IP to different VMs (SR_2016101154002)', u'320', u'Incident', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 12, 13, 56, 430000), datetime.datetime(2016, 10, 13, 7, 41, 33), datetime.datetime(2016, 10, 19, 11, 5, 59), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u' ', u'Instance affinity is only guaranteed as long as the DIP set does not change. If the DIP set changes, new connections can be routed to different DIPs. This is per design.\nLoad balanced Instance = (Hash calculated over source IP) % (number of instances probed UP)')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24458359L, 3, u'[Mooncake][21V] - [Azul_SR_2016101254130][MSSolve_SR_116101214788444][investigate why exporting database operation is pending]', u'780', u'Incident', u'4. Completed Investigation', u'Network', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 12, 16, 9, 16, 583000), datetime.datetime(2016, 10, 15, 1, 14, 58), datetime.datetime(2016, 10, 15, 1, 16, 10), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\SQLPortal', '', u'Azure SQL DB - China', u'', u'We have got 2 customers reported that export database (China East) operation was pending for a long time, during the issue time, we could repro it. But seems the issue was disappeared around 10/12 12:00 UTC. Now could you please help investigate the issue to provide RCA to customers?--->user may have ill structured data in the database\nA transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.\nThe DacFx service seems return back to a health state after October 12th.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24459040L, 4, u'Need RCA for Virtual Machine hang.', u'190', u'Root Cause', '', u'User Issue', 'other', '', datetime.datetime(2016, 10, 12, 16, 32, 13, 553000), datetime.datetime(2016, 10, 13, 15, 26, 7), datetime.datetime(2016, 10, 13, 15, 26, 39), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\IncidentManager', u'Iaas', u'RDFE - China', u'', u'During issue time wo found no platform change to your VMs but VM CPU is very high. And there are heartbeats between guest and host.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24460934L, 4, u'RCA request for mysql LSI 24419775 on 10/11', u'490', u'Root Cause', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 12, 17, 36, 9, 570000), datetime.datetime(2016, 10, 21, 10, 32, 38), datetime.datetime(2016, 10, 21, 10, 33, 14), u'RESOLVED', None, u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', '', u'MySQL Database on Azure - China', u'', u'RCA delivered')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24462255L, 4, u'NET POD | Sev 4 | Request | Can\'t successfully execute "Stop Diagnostics" for two Vnet on ACIS (SR_2016100153224 & SR_2016101153905)', u'520', u'Incident', u'4. Completed Investigation', u'Platform Change', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 18, 19, 40, 860000), datetime.datetime(2016, 10, 15, 8, 14, 10), datetime.datetime(2016, 10, 15, 8, 14, 34, 937000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Cloudnet - China', '', '', u'Cloudnet - China', u'VPN Gateway', u'The issue is remnant of an earlier issue, where the region of Gateway Tenant were put into wrong format.\nCorrected them now.\nPlease retry, this should have been fixed now.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24463605L, 4, u'pod network  | SR_2016101154011_[MS-LED]SLB can not access ', u'200', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 19, 5, 38, 307000), datetime.datetime(2016, 10, 12, 22, 23, 10), datetime.datetime(2016, 10, 12, 22, 23, 24), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u'', u'The issue was resolved by reset the Kernel parameters.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24471109L, 3, u'WATS  | Sev 3 | [MS-LED]VM is unable to connect(SR_2016101154010)', u'80', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 23, 34, 17, 20000), datetime.datetime(2016, 10, 13, 7, 49, 32), datetime.datetime(2016, 10, 13, 7, 49, 46), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WATS', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'Windows Azure Operations Center - China', u'', u'We have checked the backend the VM\u2019s DIP cannot ping successfully also,Then I checked the VM usage info, this VM\u2019s CPU is up to 100% SINCE 18:00, which matched customer reported.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24497976L, 4, u'[Mooncake][21V] - [Azul_SR_2016101153841][No MSSolve Case][investigate the reason of abnormal export database operation]', u'330', u'Incident', u'4. Completed Investigation', u'Network', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 13, 11, 32, 31, 197000), datetime.datetime(2016, 10, 15, 1, 26, 5), datetime.datetime(2016, 10, 15, 1, 26, 52), u'RESOLVED', u'Investigate', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', '', u'Azure SQL DB - China', u'', u'Escalate to SQL team-->Transfer to Managed backup team\nA transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24504854L, 4, u'check DDOS Customer of the Sub id and Customer Type ', u'300', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 13, 15, 23, 24, 457000), datetime.datetime(2016, 10, 13, 16, 15, 16), datetime.datetime(2016, 10, 13, 16, 15, 33, 463000), u'RESOLVED', '', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'', u'check DDOS Customer of the Sub id and Customer Type.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24522603L, 3, u'[Mooncake][21V] - [HDInsight][Azul_SR_2016101354352][MSSolve_SR_116101314795554/]Help us to reboot our worknode1 of hdinsight', u'110', None, u'4. Completed Investigation', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 14, 1, 50, 48, 493000), datetime.datetime(2016, 10, 14, 4, 50, 41), datetime.datetime(2016, 10, 14, 4, 52, 8), u'RESOLVED', None, u'HDInsight - China', u'HDINSIGHTCHINA\\LivesiteOnCalls', u'HDInsight - China', '', '', u'HDInsight - China', u'', u'CIE has contacted Hdinsight on-call. WASU help transfer this ticket to PG.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24539032L, 4, u'WASMS | <SR_2016100953630_Customer has bill issue during 10.4--10.10 please help to investigate if the Data transfer billing rule is correct>', u'260', u'Incident', u'2. Engaged', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 14, 9, 39, 5, 90000), datetime.datetime(2016, 10, 18, 11, 3, 21), datetime.datetime(2016, 10, 18, 11, 4, 17), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-BillingPlatform', u'WASU', u'AAD Customer Acquisition and Billing - China', u'', u'Escalate to Billing team--->trying to track down the owner of the data monitor \u2013 it seems like they should own this incident, because the portal/bill are showing the right data as per your analysis below.-->It should be commerce issue instead of Billing portal')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24540431L, 4, u'Networking | Virtual Networking |[RCA] vm networking out data is abnormal from 2016/10/4 to 2016/10/10 CST(SR_2016101153872)', u'90', u'Root Cause', '', u'Duplicate', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 14, 10, 11, 41, 960000), datetime.datetime(2016, 10, 19, 13, 49, 56), datetime.datetime(2016, 10, 19, 13, 50, 25, 840000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'abnormal data out', u'Same ticket as\xa024401415')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24543511L, 3, u'Networking | Virtual Networking | Internal [HMC] Error occures when upload Application Gateway config file(SR_2016101354276)', u'220', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 14, 11, 51, 18, 530000), datetime.datetime(2016, 10, 15, 8, 20, 40), datetime.datetime(2016, 10, 15, 8, 21, 35), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\ApplicationGateway', u'Cloudnet - China', u'CLOUDNETCHINA\\ApplicationGateway', '', u'Cloudnet - China', u'packet drop', u'Escalate to App GW team--->This issue should be fixed with a fleet upgrade (of application gateways) in Mooncake.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24546766L, 3, u'WATS | Networking | VNET | [MS-LED]Unable to update configuration for VNET in new portal (SR_2016101454416)', u'450', u'Incident', u'3. Confirmed Ownership', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 14, 13, 23, 58, 487000), datetime.datetime(2016, 10, 21, 9, 55, 23), datetime.datetime(2016, 10, 21, 9, 55, 41), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'packet drop', u'escalate to Brooklyn team--->The issue is with provisioning of an ER Gateway --> PG suggest to resize GW')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24546809L, 3, u'[Mooncake] WA-TRAFFIC|Failed to add new endpoint', u'820', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 14, 13, 25, 48, 860000), datetime.datetime(2016, 10, 22, 8, 18, 45), datetime.datetime(2016, 10, 22, 8, 19), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\DNS', u'Azure DNS', u'Cloudnet - China', u'', u'this is a platform bug in the logic to find the authoritative DNS server for customer endpoint and will be fixed in next released.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24550739L, 4, u'[POD VMA] WATS | IcM | Sev 4 | [MS-LED]Pls to investigation VM Restart Cause (SR_2016101454392)', u'640', u'Root Cause', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 14, 15, 34, 45, 970000), datetime.datetime(2016, 10, 18, 13, 43, 18), datetime.datetime(2016, 10, 18, 13, 43, 40), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', u'RDOSCHINA\\AzureHost-Sev-3-4', '', u'RDOS - China', u'CRI', u'escalate to CHost team --> this is a bug')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24610307L, 4, u'WATS | Podplat | [MS-LED]cannot create VM successfully(SR_2016101554520)', u'460', '', u'2. Engaged', u'ByDesign', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 15, 19, 26, 14, 63000), datetime.datetime(2016, 10, 20, 5, 59, 5), datetime.datetime(2016, 10, 20, 5, 59, 16), u'RESOLVED', None, u'RDFE - China', u'AZURERTCHINA\\IaaS', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'RDFE - China', u'', u'one operation did not completed, but no detail for its operation id. --> escalate to RDFE to check this issue operation.-->Talk with\xa0Amandeep and he will take a look and update the mail')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24660595L, 3, u'IcM request |service fabric provisioning failed issue ', u'720', '', u'4. Completed Investigation', u'Network', 'CSS', u'CSS-Shanghai', datetime.datetime(2016, 10, 17, 11, 47, 17, 110000), datetime.datetime(2016, 10, 26, 0, 44, 38), datetime.datetime(2016, 10, 26, 0, 44, 52, 90000), u'RESOLVED', None, u'Service Fabric - Service - China', u'WINDOWSFABRICCHINA\\WindowsFabricService', u'RDFE - China', u'AZURERTCHINA\\CRPCoreService', u'CoreRP_CRP', u'Service Fabric - Service - China', u'', u'We have got over the issue and the ticket can be closed now.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24663512L, 3, u'[Mooncake] | Service Fabric  | Failed to create fabric service On the ibiza portal ', u'1125', u'Incident', '', u'LSI', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 17, 14, 4, 42, 233000), datetime.datetime(2016, 10, 19, 14, 36, 9), datetime.datetime(2016, 10, 21, 2, 58, 11, 930000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'ESTS - China', u'WINDOWSFABRICCHINA\\Triage', '', u'Service Fabric - Service - China', u'', u'service is GA but extension on ibiza portal is not GA, need customer feedback and PG team is looking for publish status from portalfx team.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24664146L, 3, u'check subs', u'100', '', '', u'Diagnostics Data Collection', 'other', '', datetime.datetime(2016, 10, 17, 14, 30, 52, 633000), datetime.datetime(2016, 10, 17, 16, 35, 38), datetime.datetime(2016, 10, 17, 16, 35, 57, 637000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\CC', u'CC', u'Windows Azure Operations Center - China', u'', u'Finsih the check operation')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24664498L, 3, u'WATS | VPN | [MS-LED]Unable to see the function bottom for creating VPN gateway (SR_2016101754615)', u'80', u'Incident', u'2. Engaged', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 17, 14, 46, 27, 910000), datetime.datetime(2016, 10, 17, 15, 56, 25), datetime.datetime(2016, 10, 17, 15, 56, 51), u'RESOLVED', u'Triage', u'Azure UX - China', u'AZUREUXCHINA\\AUXPortal', u'Azure UX - China', u'AZUREUXCHINA\\AUXPortal', '', u'Azure UX - China', u'VPN Gateway', u"It's should be customer issue.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24669343L, 4, u'pod plat | SR_2016101554515_[MS-LED]check vm status cpu etc.', u'90', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 17, 17, 47, 6, 187000), datetime.datetime(2016, 10, 18, 13, 18, 3), datetime.datetime(2016, 10, 18, 13, 18, 30, 257000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'RDOS - China', u'RDOSCHINA\\AzureHost-Sev-3-4', u'WASU', u'Windows Azure Operations Center - China', u'', u'Had sent the mds table and data to wats.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24670042L, 3, u'Networking | Virtual Networking | package drop (SR_2016101053679_[MS-LED] Guangdong Mobile 4G access Azure is unnormal)', u'420', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 17, 18, 15, 51, 710000), datetime.datetime(2016, 10, 19, 16, 43, 54), datetime.datetime(2016, 10, 19, 16, 45, 14), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'packet drop', u'No slb issue or platform issue')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24672339L, 3, u'Networking | Virtual Networking | delay time high (SR_2016101754669\u2009_\u2009[MS-LED]delay too high)', u'120', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 17, 19, 53, 42, 420000), datetime.datetime(2016, 10, 17, 21, 31, 56), datetime.datetime(2016, 10, 18, 8, 27, 16), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'delay time high', u'Escalated to IM.\nUser issue. Latency is normal and packet loss is acceptable.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24677047L, 2, u' ExpressRoute |  Not able to connect through ER private circuit ', u'1120', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 17, 22, 51, 14, 707000), datetime.datetime(2016, 10, 18, 18, 42, 52), datetime.datetime(2016, 10, 19, 12, 28), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\ExpressRoute', u'Cloudnet - China', u'CLOUDNETCHINA\\ExpressRoute', u'EXPRESSROUTE', u'Cloudnet - China', u'Express Route', u"mitigated the issue as failover the primary instance for GWT. It's platform bug.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24697830L, 3, u'WA-IAAS|VM Activation Issue|    WATS |  [MS-LED]', u'310', u'Incident', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 18, 8, 54, 40, 447000), datetime.datetime(2016, 10, 20, 1, 37, 59), datetime.datetime(2016, 10, 20, 1, 40, 10), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'RDFE - China', u'CRI,Activation', u'escalate to rdfe/IAAS to tracking activate failed\xa0issue-->This is by design now, and KMS team will update the server before there is some impact with Windows Server 2016')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24699322L, 4, u'test for azure  web apps', u'25', '', '', u'Test Deployment', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 18, 9, 41, 4, 447000), datetime.datetime(2016, 10, 20, 18, 33, 7), datetime.datetime(2016, 10, 20, 18, 33, 20), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'CIE', u'App Service (Web Apps) - China', '', '', u'Windows Azure Operations Center - China', u'', u'test for azure\xa0 web apps')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24699943L, 4, u'[Pod Net] | Virtual Networking | Network Connection Timeout (SR_2016101854710)', u'80', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 18, 9, 57, 10, 560000), datetime.datetime(2016, 10, 19, 13, 2, 44), datetime.datetime(2016, 10, 19, 13, 3, 25), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'Network Connection Timeout', u'through reverse trace and ping test latency time is normal, and no loss packet issue in Guangdong lease line')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24700388L, 4, u'WATS | Virtual Networking | Reasons for slow network access_SR_2016101854714 | RCA', u'700', u'Root Cause', u'4. Completed Investigation', u'Network', 'other', '', datetime.datetime(2016, 10, 18, 10, 13, 43, 827000), datetime.datetime(2016, 10, 19, 8, 22, 33), datetime.datetime(2016, 10, 19, 8, 24, 21), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'WASU', u'Cloudnet - China', u'', u'The network unstable due to high regional traffic volumes. Provided RCA to requestor.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24707200L, 3, u'Networking | Virtual Networking | packet drop (SR_2016101854727\u2009_\u2009network package lost)', u'140', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 18, 14, 19, 12, 420000), datetime.datetime(2016, 10, 19, 14, 4, 42), datetime.datetime(2016, 10, 19, 14, 7, 17, 773000), u'RESOLVED', u'Triage', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop', u'Got WATS confrimation to resolved this\xa0ticket.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24707919L, 3, u'Network | Brooklyn | VPN Gateway Issue (SR_2016100653281)', u'200', u'Incident', '', u'Duplicate', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 18, 14, 44, 43, 463000), datetime.datetime(2016, 10, 19, 7, 57, 38), datetime.datetime(2016, 10, 19, 7, 57, 54), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u'duplicated issue')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24710731L, 3, u'suspend deployment IDs', u'60', '', '', u'Update Subscription Setting', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 18, 15, 48, 35, 527000), datetime.datetime(2016, 10, 18, 16, 6, 36), datetime.datetime(2016, 10, 18, 16, 6, 58), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'done.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24710829L, 4, u'WATS | Sev 3 | [MS-LED] Check VM "wlyd-50yc-mys1" CPU usage(SR_2016101754580)', u'180', '', '', u'Diagnostics Data Collection', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 18, 15, 51, 7, 200000), datetime.datetime(2016, 10, 19, 18, 0, 45), datetime.datetime(2016, 10, 19, 18, 1, 19), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Xstore - China', '', u'Storage', u'Windows Azure Operations Center - China', u'', u'We have told the method of check the VPU usage.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24712027L, 3, u'suspend Sub', u'10', '', '', u'Update Subscription Setting', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 18, 16, 29, 0, 627000), datetime.datetime(2016, 10, 18, 19, 28, 56), datetime.datetime(2016, 10, 18, 19, 29, 7), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASMS', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'', u'transfter ticket to WASMS,add effort--->Done by WASMS')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24712391L, 4, u'pod plat | SR_2016101854764_can not connect azure storage', u'120', u'Incident', u'4. Completed Investigation', u'User Issue', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 18, 16, 39, 32, 763000), datetime.datetime(2016, 10, 19, 9, 4, 33), datetime.datetime(2016, 10, 20, 18, 31, 36), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Windows Azure Operations Center - China', u'XSTORECHINA\\Triage', u'WASU', u'Xstore - China', u'', u'Escalated to xstore team for help.\nUser issue')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24750236L, 2, u'[Mooncake][21V] - [Azul_SR_2016101954907][MSSolve_SR_116101914818356/failed to update db', u'480', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 19, 9, 52, 29, 370000), datetime.datetime(2016, 10, 19, 11, 58, 40), datetime.datetime(2016, 10, 19, 12, 56, 40), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\GeoDR', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Provisioning', '', u'Azure SQL DB - China', u'', u'The update slo was stuck in copying/seeding state and was mitigated by recycling the primary replica, customer need to wait for around 3 hours to get the db migrated after operated.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24753338L, 3, u"Networking | Virtual Networking | BM can't access user server (SR_2016101954927\u2009_\u2009[MS-LED]Beijing Area Mobile network can't access user server\u2009)", u'45', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 19, 10, 56, 52, 60000), datetime.datetime(2016, 10, 21, 9, 53, 16), datetime.datetime(2016, 10, 21, 9, 53, 34, 980000), u'RESOLVED', u'Triage', u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop', u'Customer not provider some info.WATS agree close this ticket')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24757279L, 3, u'[Mooncake][21V] - [RCA][Azul_SR_2016101954907 ][MSSolve_SR_116101914818185/rca for db upgrading failure.', u'240', u'Root Cause', u'1. Contacted', u'Platform Bug', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 19, 13, 8, 15, 943000), datetime.datetime(2016, 10, 22, 6, 56, 5), datetime.datetime(2016, 10, 22, 7, 52, 56), u'RESOLVED', u'Investigate', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\GeoDR', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\GeoDR', '', u'Azure SQL DB - China', u'', u'RCA request for incident\xa024750236, escalated to SQL GeoDr for help')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24765412L, 4, u'Sev 4 | CRI 24765412 |WA-IaaS|Unexpected restart or shutdownRCA(SR_2016101955026)', u'210', u'Incident', '', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 19, 17, 50, 20, 460000), datetime.datetime(2016, 10, 20, 9, 47, 35), datetime.datetime(2016, 10, 20, 9, 47, 53, 740000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'CRI', u'The node got unhealthy which resulted in the reboot of\xa0 VM, delivered the TenantHistory and NodeStateChanges info to WATS')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24768356L, 3, u'[Mooncake]| Redis Cache| Redis read time out', u'180', u'Incident', '', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 19, 19, 27, 54, 170000), datetime.datetime(2016, 10, 20, 9, 43, 16), datetime.datetime(2016, 10, 20, 20, 24, 21), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Redis Cache - China', '', u'REDIS Managed Cache Service', u'Windows Azure Operations Center - China', u'CRI,AzureCache', u'seems the CPU is very high and the server load is almost 100%.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24858195L, 3, u'Networking | Virtual Networking | Slow connectivity to US servers(SR_2016102055071)', u'120', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 21, 9, 49, 6, 237000), datetime.datetime(2016, 10, 27, 9, 26, 28), datetime.datetime(2016, 10, 27, 9, 26, 48, 300000), u'RESOLVED', u'Triage', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop and slow', u'Confirm with WATS, could close the incident.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24867034L, 4, u'Please help to check customer information for IP 139.219.137.160', u'60', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 21, 14, 34, 29, 950000), datetime.datetime(2016, 10, 21, 23, 28, 30), datetime.datetime(2016, 10, 21, 23, 28, 46), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'Done.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24871538L, 4, u'Suspend deployment', u'30', '', '', u'Update Subscription Setting', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 21, 16, 53, 27, 460000), datetime.datetime(2016, 10, 21, 17, 48, 31), datetime.datetime(2016, 10, 21, 17, 48, 53, 730000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'', u"Suspend customer's deployment--->Deployment suspended")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24871803L, 3, u'WA-IaaS|Inaccessible Linux VM| | HMC | vm cannot start_(SR_2016102155389) ', u'600', u'Incident', '', u'Platform Change', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 21, 17, 2, 42, 250000), datetime.datetime(2016, 10, 24, 9, 21, 58), datetime.datetime(2016, 10, 24, 9, 22, 10), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Compute Manager - China', u'COMPUTEMANAGERMOONCAKE\\ContainerManager', '', u'Compute Manager - China', u'CRI', u'Noticed the host node is in ready sstate. - -> Suggest customer to try to start again. ---- > From Backend, the VM was running state.\xa0 ---> Waiting for the cutomer confirm if the issue was mitigated.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24873419L, 3, u'Networking | Virtual Networking | SLB packet drop (SR_2016092652344\u2009_\u2009[MS-LED]access someone ip be refused\u2009)', u'500', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 21, 17, 44, 43, 827000), datetime.datetime(2016, 10, 21, 19, 50, 42), datetime.datetime(2016, 10, 25, 14, 59, 33), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'AutoPilot SLB', u'Cloudnet - China', u'packet drop', u'SLB no issue.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24873658L, 3, u'WATS | Podnet | [MS-LED]help to confirm if existing some network issue from customer location to Azure(SR_2016102155395)', u'230', u'Incident', u'2. Engaged', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 21, 17, 49, 42, 750000), datetime.datetime(2016, 10, 24, 10, 44, 58), datetime.datetime(2016, 10, 24, 10, 45, 18, 410000), u'RESOLVED', u'Blocked', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'WASU', u'Cloudnet - China', u'', u'Customer issue.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24934113L, 4, u'Please help to complete the statistics, thanks', u'600', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 22, 19, 58, 2, 217000), datetime.datetime(2016, 10, 22, 23, 35, 10), datetime.datetime(2016, 10, 22, 23, 35, 30), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'check subs')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24983356L, 4, u'WASMS | <SR_2016101955046 1RMB Data transfer query >', u'240', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 24, 10, 15, 7, 380000), datetime.datetime(2016, 10, 24, 15, 9, 34), datetime.datetime(2016, 10, 24, 15, 10, 23), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'We check the date transfer is match with Usage report except 10/23/2016.And no find any DDOS happend to the customer during the time .')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24985829L, 4, u'Network | Brooklyn | [RCA] VPN Gateway Issue (SR_2016102455546)', u'380', u'Root Cause', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 24, 12, 14, 57, 490000), datetime.datetime(2016, 10, 24, 16, 1, 32), datetime.datetime(2016, 10, 24, 16, 2, 8), u'RESOLVED', u'Blocked', u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u"During\xa019:50 ~ 19:55 and 20:05 ~ 20:10 S2SNumConnectedSites was decreased to 0, around that time, the max throughput of GW is 192 Mbps, but customer's GW size is basic, which has 100 Mbps capacity. So the RCA should be that the real throughput of GW was more than 100 Mbps.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24985929L, 3, u'21V [Ford] | [SR_2016102255449]- Cant create servcie fabric with resource template in powershell now !', u'2900', u'Incident', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 24, 12, 19, 23, 277000), datetime.datetime(2016, 10, 25, 6, 56, 23), datetime.datetime(2016, 10, 25, 13, 2, 44, 777000), u'RESOLVED', None, u'Service Fabric - Service - China', u'WINDOWSFABRICCHINA\\WindowsFabricService', u'Service Fabric - Service - China', '', '', u'Service Fabric - Service - China', u'21V', u'could repro from Powershell and escalated to PG team --> we have LSI to check this issue--->After Vaishnav and WADE Team deployed a new configuration file on the Service Fabric RP backend using actual built, the issue was mitigated.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24988437L, 4, u'[POD VMA] | RCA | Inaccessible Linux VM| | HMC | vm cannot start_(SR_2016102155389)', u'1400', u'Root Cause', u'4. Completed Investigation', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 24, 14, 13, 44, 843000), datetime.datetime(2016, 10, 28, 13, 38, 31), datetime.datetime(2016, 10, 28, 13, 38, 47, 247000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASH', u'Compute Manager - China', u'RDOSCHINA\\AzureHost-Sev-3-4', '', u'RDOS - China', u'CRI', u'bad nodes : 05690861-0000-0000-0000-008cfa50cff4 and 05711155-0000-0000-0000-008cfa50b188, have been OFRed.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24990352L, 3, u'Not able to connect Azure SQL with some error', u'480', u'Incident', '', u'Capacity', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 24, 15, 33, 28, 773000), datetime.datetime(2016, 10, 25, 8, 22, 42), datetime.datetime(2016, 10, 26, 10, 5, 55), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Office365 SuiteUX - China', u'OFFICE365SUITEUXCHINA\\Gallatinoncall', '', u'Azure SQL DB - China', u'', u'The database is basic, which is not enough to meet the requirements. Suggest to scale to standard or premium.Confirm with customer the issue was resolved.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24990535L, 4, u'Network | ExpressRoute | Enable ER permissions (SR_2016102455622)', u'45', u'Incident', '', u'Update Subscription Setting', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 24, 15, 42, 15, 533000), datetime.datetime(2016, 10, 24, 16, 18, 12), datetime.datetime(2016, 10, 24, 16, 19, 11, 747000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'Express Route', u'enabled ER permissions')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24993654L, 3, u'WASMS | < OrgID used as Contact Email during sign up process>', u'1840', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 24, 17, 45, 35, 97000), datetime.datetime(2016, 10, 27, 9, 6, 58), datetime.datetime(2016, 11, 9, 10, 46, 3, 60000), u'RESOLVED', None, u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-Experiences', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-BillingPlatform', u'WASU', u'AAD Customer Acquisition and Billing - China', u'', u'For the impacted customer issue fixed, have attached the list to email and ICM. From Tarek, they do not have capacity to write a tool to specifically fix this data issue.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (24994018L, 3, u'WATS | Networking | unable to connect with server (on-premises) from VM inside (SR_2016102455657)', u'80', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 24, 18, 3, 26, 297000), datetime.datetime(2016, 10, 24, 20, 11, 17), datetime.datetime(2016, 10, 24, 20, 15, 51), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', '', '', u'Cloudnet - China', u'packet drop', u'need more info --> user issue')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25023997L, 4, u'Networking | Virtual Networking | cant not establish tcp/udp session from CT end user to Azure VM (SR_2016101754694)', u'165', u'Incident', '', u'Problem Unidentified', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 25, 9, 34, 10, 103000), datetime.datetime(2016, 10, 30, 18, 8, 41), datetime.datetime(2016, 10, 30, 18, 9, 8, 520000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'can not establish tcp/udp session', u'Need wats provider more info,resolved as no feedback from cx for long time.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25025588L, 4, u"Standby Bridge for Single's Day", u'9120', '', u'4. Completed Investigation', u'Diagnostics Data Collection', 'other', '', datetime.datetime(2016, 10, 25, 10, 14, 49, 807000), datetime.datetime(2016, 11, 12, 12, 43, 10), datetime.datetime(2016, 11, 12, 12, 45, 20), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'Windows Azure Operations Center - China', u'', '')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25026823L, 3, u'WASMS | The billed amount display as double tax in account portal.', u'110', u'Incident', '', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 25, 10, 56, 17, 860000), datetime.datetime(2016, 10, 25, 12, 12, 53), datetime.datetime(2016, 10, 25, 12, 14, 34), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'The issue\xa0is CMAT\xa0issue. And\xa0commerce team will be\xa0able to help to follow up\xa0based on the ticket ID.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25028826L, 3, u'[Mooncake][21V] - [Azul_SR_2016102455695][MSSolve_SR_116102414841427][Scale database is not working on v11 server] ', u'70', u'Incident', '', u'Platform Change', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 25, 12, 5, 27, 577000), datetime.datetime(2016, 10, 25, 14, 8, 9), datetime.datetime(2016, 10, 25, 14, 9, 25), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Azure SQL DB - China', '', '', u'Windows Azure Operations Center - China', u'', u'Per offline talk, the customer want to update the server to V12, but PG suggest let customer update the server by himself. Pod DB\xa0\xa0will escalate to Azure SQL DB directly.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25031571L, 4, u"21V [Ford]|[SR_2016102255449]- RCA for  Service Fabric can't create success ", u'160', u'Root Cause', '', u'LSI', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 25, 13, 48, 21, 423000), datetime.datetime(2016, 10, 26, 4, 49, 25), datetime.datetime(2016, 10, 28, 9, 58, 35), u'RESOLVED', None, u'Service Fabric - Service - China', u'WINDOWSFABRICCHINA\\WindowsFabricService', u'Service Fabric - Service - China', u'WINDOWSFABRICCHINA\\Triage', '', u'Service Fabric - Service - China', u'21V', u'public RCA request for LSI\xa024990388')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25087392L, 4, u'check subs', u'35', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 26, 10, 18, 43, 547000), datetime.datetime(2016, 10, 26, 11, 11, 49), datetime.datetime(2016, 10, 26, 11, 12, 11, 267000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\CC', u'CC', u'Windows Azure Operations Center - China', u'', u'check the info of ip.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25088449L, 3, u'[Mooncake]:[ServiceBus]/eventhub cannot create consumer', u'180', u'Incident', u'4. Completed Investigation', u'ByDesign', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 26, 10, 51, 22, 630000), datetime.datetime(2016, 10, 28, 2, 12, 18), datetime.datetime(2016, 10, 28, 2, 12, 49), u'RESOLVED', None, u'Service Bus - China', u'SERVICEBUSCHINA\\DRI-Queues/Topics/EventHubs', u'Service Bus - China', u'SERVICEBUSCHINA\\DRI-Queues/Topics/EventHubs', u'Broker', u'Service Fabric - Service - China', u'', u'Namespace with basic sku cannot create new ConsumerGroups.\nBasic can only have 1 CG https://azure.microsoft.com/en-us/pricing/details/event-hubs/\nthe customer deleted the namespace')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25096567L, 4, u'Check IP for IM', u'80', u'Other', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 26, 15, 37, 9, 393000), datetime.datetime(2016, 10, 26, 15, 46, 57), datetime.datetime(2016, 10, 26, 15, 47, 29, 80000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'Help IM check ip')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25096713L, 4, u'WASMS | check MySQL data base usage-SR#2016102555826', u'200', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 26, 15, 43, 12, 850000), datetime.datetime(2016, 10, 27, 13, 37, 34), datetime.datetime(2016, 10, 27, 13, 38, 12), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'Support', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', u'InstanceAgent', u'MySQL Database on Azure - China', u'', u'we can see the bill should match customer\u2019s screenshot.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25098033L, 4, u'WATS | Make diskSizeGB available for all disks in ARM (SR_2016102455568)', u'230', u'Incident', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 26, 16, 35, 49, 47000), datetime.datetime(2016, 10, 27, 10, 18, 35), datetime.datetime(2016, 10, 27, 10, 19, 43), u'RESOLVED', None, u'RDFE - China', u'AZURERTCHINA\\CRPCoreService', u'RDFE - China', u'AZURERTCHINA\\CRPCoreService', u'CoreRP_CRP', u'Windows Azure Operations Center - China', u'CRI', u'This is by design but we have a bug to fix this: 6287874')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25099858L, 3, u'Networking | Virtual Networking | Higher network latency SR_2016102656039\u2009_\u2009Higher network latency\u2009', u'150', u'Incident', '', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 26, 17, 49, 26, 307000), datetime.datetime(2016, 10, 31, 8, 49, 16), datetime.datetime(2016, 10, 31, 8, 49, 45), u'RESOLVED', u'Blocked', u'Windows Azure Operations Center - China', u'Support', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop', u'escalate to IM --> CT link issue.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25141599L, 4, u'The vm MYDBVM-18 shutdown unexpectedly', u'120', u'Root Cause', '', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 27, 13, 22, 16, 903000), datetime.datetime(2016, 10, 27, 14, 29, 48), datetime.datetime(2016, 10, 27, 14, 30, 39), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\IncidentManager', u'InstanceAgent', u'MySQL Database on Azure - China', u'', u'VM was rebooted because of service healing triggered by HI.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25148864L, 3, u'Customer cannot create new VM of Ubuntu 14.04 by Ibiza(SR_2016102756241)', u'480', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 27, 17, 38, 12, 290000), datetime.datetime(2016, 10, 29, 11, 13, 35), datetime.datetime(2016, 10, 29, 11, 14, 59), u'RESOLVED', u'Blocked', u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', u'COMPUTEMANAGERMOONCAKE\\ContainerManager', '', u'Compute Manager - China', u'CRI', u'can not\xa0create VM of Ubuntu 14.04 by Ibiza.-->\nWe found this Deployment Templates \xa0"sku": "14.04.5-LTS", but the \xa0backend doesn\u2019t have this SKU.\nhttps://gallery.windowsazure.cn/artifact/20151001/Canonical.UbuntuServer1404LTS-ARM.1.0.2/DeploymentTemplates/createuidefinition.json\xa0--> can create now.reslove the ticket')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25149250L, 3, u'sql database can not be scaled up from management portal.', u'180', u'Incident', '', u'ByDesign', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 27, 17, 55, 30, 257000), datetime.datetime(2016, 10, 28, 10, 51, 43), datetime.datetime(2016, 10, 28, 10, 52, 23, 537000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\SQLPortal', '', u'Azure SQL DB - China', u'', u"Confirmed with customer, the db has been upgraded into v12 now, and the function are recovered. It's by design that for V11\xa0 database can't support scale up from management portal but powershell.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25197232L, 4, u'WA-IaaS|Inaccessible Windows VM|Unexpected restart or shutdown_SR_2016102856443', u'170', u'Root Cause', '', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 28, 18, 35, 23, 890000), datetime.datetime(2016, 10, 28, 22, 26, 43), datetime.datetime(2016, 10, 28, 22, 27, 33), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Compute Manager - China', '', '', u'Compute Manager - China', u'', u'We find the node unhealthy at 2016-10-28T07:46:17.6891517.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25197680L, 3, u'[Mooncake]WA-Storage| cannot list container which contains appendblob in classic portal', u'215', u'Incident', u'4. Completed Investigation', u'ByDesign', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 28, 18, 52, 32, 977000), datetime.datetime(2016, 10, 29, 7, 59, 42), datetime.datetime(2016, 10, 29, 8, 0, 28), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Xstore - China', '', u'Storage', u'Xstore - China', u'', u'Escalate to storage team --> transfer to portal team --> not supportted by classic portal')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25233730L, 4, u'customer information inquiry', u'120', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 29, 14, 23, 22, 530000), datetime.datetime(2016, 10, 29, 15, 59, 52), datetime.datetime(2016, 10, 29, 16, 0, 9), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'CC', u'Windows Azure Operations Center - China', u'', u'check subs')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25277149L, 4, u'check subs', u'400', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 30, 20, 22, 13, 683000), datetime.datetime(2016, 10, 30, 23, 14, 21), datetime.datetime(2016, 10, 30, 23, 14, 38), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'CC', u'Windows Azure Operations Center - China', u'', u'have provide sub ID to CSS team')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25277434L, 4, u'check subs', u'70', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 30, 20, 36, 53, 830000), datetime.datetime(2016, 10, 30, 21, 42, 6), datetime.datetime(2016, 10, 30, 21, 42, 18, 670000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'CC', u'Windows Azure Operations Center - China', u'', u'done with the request for checking IP')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25298502L, 3, u'WA-IaaS|Sev 3 | The VM failed to start(SR_2016103156577)', u'635', u'Incident', u'4. Completed Investigation', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 31, 11, 16, 49, 80000), datetime.datetime(2016, 11, 1, 8, 34, 9), datetime.datetime(2016, 11, 1, 9, 5, 42), u'RESOLVED', None, u'Azure Hardware Datacenter Manager - China', u'AZUREHARDWAREDATACENTERMANAGERCHINA\\DatacenterPlatform-LowPri', u'RDOS - China', u'RDOSCHINA\\AzureHost-Sev-3-4', u'WASU', u'RDOS - China', u'', u"he VM(A7) can't start on the on the 2016/10/30 (UTC). We escalated to RDos team. -->\xa0\xa0Francis David ask WALS to OFR the node --> transfer to DCM-> vm bjtdxhq12 scaled up to A7, nothing we can do here, so we resolved.")
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25304912L, 3, u'WASMS | 1RMB offer topped off 1000CNY but still shows 1RMB offer', u'460', u'Incident', '', u'Billing -Valid Billing ', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 31, 15, 53, 58, 713000), datetime.datetime(2016, 10, 31, 18, 16, 13), datetime.datetime(2016, 10, 31, 18, 16, 22), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-Experiences', '', u'Windows Azure Operations Center - China', u'', u'RDFE and billing portal component recieved correct calling and need Payops to check from commerce side.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25307280L, 4, u'RCA-[Mooncake]:[NotificationHub]notification hub lose messages ', u'440', u'Root Cause', '', u'Problem Unidentified', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 31, 17, 24, 25, 237000), datetime.datetime(2016, 11, 7, 8, 36, 14), datetime.datetime(2016, 11, 7, 8, 36, 34, 910000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'Support', u'Azure Notification Hub - China', '', '', u'Azure Notification Hub - China', u'', u'Waiting for the feedback from customer, but no response for more than 4 days.')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25310475L, 4, u'Please help check Subscription Id and Deployment ID for 2 Ips\uff1a139.217.8.188; 139.217.9.174', u'150', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 31, 19, 38, 16, 737000), datetime.datetime(2016, 10, 31, 22, 26, 2), datetime.datetime(2016, 10, 31, 22, 26, 42, 203000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'have done the request for ip')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25315037L, 4, u'ICP| please help check IPs', u'80', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 31, 22, 31, 56, 537000), datetime.datetime(2016, 10, 31, 23, 12, 14), datetime.datetime(2016, 10, 31, 23, 12, 27, 150000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'done with the request')
Tue, 15 Nov 2016 01:38:55:insert_logs.py[line:35] INFO (25316568L, 3, u'[Mooncake][21V] - [HDInsight][Azul_SR_2016103156631][MSSolve_SR_116103114869926][Failed to connect to HBase with HTTPS]', u'550', u'Incident', u'3. Confirmed Ownership', u'User Issue', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 31, 23, 24, 21, 580000), datetime.datetime(2016, 11, 1, 23, 41, 25), datetime.datetime(2016, 11, 1, 23, 42, 2), u'RESOLVED', u'Investigate', u'HDInsight - China', u'HDINSIGHTCHINA\\LivesiteOnCalls', u'HDInsight - China', u'HDINSIGHTCHINA\\HBase', '', u'HDInsight - China', u'', u"it shows that we have no 403 error from our own watchdog accessing that customer cluster so it doesn't look like a problem in gateway code. Please ask customer to double check the password they are using in their script.\nAlso, once the bad password is used for\xa0serveral times, the user will be locked out for a while even correct password is use.")
Tue, 15 Nov 2016 01:38:57:insert_logs.py[line:24] INFO Insert execl Done!
Tue, 15 Nov 2016 01:38:57:insert_logs.py[line:24] INFO Run done!
Wed, 30 Nov 2016 15:38:50:MS_DB_query.py[line:41] INFO Warwhouse connect issue!
Wed, 30 Nov 2016 15:39:06:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Wed, 30 Nov 2016 15:39:29:MS_DB_query.py[line:158] INFO Start Query Db.....
Wed, 30 Nov 2016 15:39:29:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:24] INFO Db  get_icm_azure_info Done!
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24360178L, 3, u'Networking | Virtual Networking | ISP link check (SR_2016101053679_[MS-LED]Guangzhou Mobile 4G access Azure is unnormal)', u'150', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 10, 10, 9, 33, 447000), datetime.datetime(2016, 10, 11, 8, 42, 42), datetime.datetime(2016, 10, 11, 8, 43, 9), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'ISP link', u'all good from Azure network,\xa0external ISP issue, need customer to engage local ISP for further look.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24362612L, 4, u'[VMA] WA-IaaS | Unexpected restart_SR_2016101053668', u'290', u'Root Cause', '', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 10, 11, 56, 4, 920000), datetime.datetime(2016, 10, 11, 11, 59, 12), datetime.datetime(2016, 10, 11, 11, 59, 27), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'CRI', u'hardware issue, single instance, gave RCA.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24364330L, 4, u'sub which is deleted could not recharge, but customer can recharge for 1000 RMB', u'1100', '', u'4. Completed Investigation', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 10, 13, 4, 24, 243000), datetime.datetime(2016, 10, 17, 9, 10, 38), datetime.datetime(2016, 10, 17, 9, 11, 11), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\AzureBusinessOperations', u'WASU', u'AAD Customer Acquisition and Billing - China', u'do not receive 1000RMB refund', u"wait for customer's screenshot.-->Escalate to Billing portal team->Tier2 - Experiences-->It should be Commerce team issue")
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24369237L, 4, u'Do we have any planed schedule or other workaround to fix the SNAT ports overload issue', u'300', '', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 10, 10, 16, 48, 46, 467000), datetime.datetime(2016, 10, 11, 5, 58, 6), datetime.datetime(2016, 10, 11, 6, 1, 23), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'AutoPilot SLB', u'Cloudnet - China', u'', u"SLB 11.15 is rolling out Static Snat feature which will help alleviate the SNAT port overload issue. If any customers are in urgent need, we can try apply it on these customer's deployments selectively even today. We have a TSG #5700189 for this purpose.")
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24377069L, 2, u'[Mooncake][21V] - [HDInsight][Azul_SR_2016100753325][MSSolve_SR_116101014777668][HBase cluster regionserver service restarted frequently]', u'615', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 10, 22, 16, 45, 173000), datetime.datetime(2016, 10, 11, 0, 51, 57), datetime.datetime(2016, 10, 19, 13, 33, 7), u'RESOLVED', '', u'HDInsight - China', u'HDINSIGHTCHINA\\LivesiteOnCalls', u'HDInsight - China', u'HDINSIGHTCHINA\\HBase', '', u'HDInsight - China', u'', u'provided solution and waiting for customer feedback.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24377697L, 3, u"MoonCake | WebSites | Can't delete newly created app service plan in new  portal (SR_2016101053819)", u'400', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-WebApp', datetime.datetime(2016, 10, 10, 22, 44, 29, 167000), datetime.datetime(2016, 10, 12, 7, 24, 2), datetime.datetime(2016, 10, 12, 7, 24, 28), u'RESOLVED', None, u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'WebSites', u'App Service (Web Apps) - China', u'', u'Have escalated to PG for help.\nTravis is working on this. Navy has updated mooncake manifest. This issue is mitigated.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24401005L, 4, u'check IP 42.159.145.75', u'40', '', '', u'Diagnostics Data Collection', 'other', '', datetime.datetime(2016, 10, 11, 9, 28, 3, 927000), datetime.datetime(2016, 10, 11, 10, 4, 14), datetime.datetime(2016, 10, 11, 10, 4, 32, 283000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'CC', u'Windows Azure Operations Center - China', u'', u'done with the request.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24401415L, 4, u'WASMS | <SR_2016100953630_Please help to check if the Data transfer usage is match with Usage report >', u'75', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 11, 9, 39, 0, 187000), datetime.datetime(2016, 10, 11, 11, 1, 40), datetime.datetime(2016, 10, 11, 11, 1, 49, 517000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'Check the backend, and the usage is match to the bill')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24403659L, 4, u'check subs & sitenames', u'110', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 11, 10, 56, 0, 520000), datetime.datetime(2016, 10, 11, 14, 23, 44), datetime.datetime(2016, 10, 11, 14, 23, 56, 217000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\CC', u'CC', u'Windows Azure Operations Center - China', u'check subs & sitenames', u'finished check')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24407571L, 4, u'[Mooncake][21V] - [Azul_SR_2016101153880][No MSSolve Case][help to cancel exporting database request]', u'199', u'Incident', '', u'Human Error', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 11, 13, 34, 31, 337000), datetime.datetime(2016, 10, 12, 8, 12, 29), datetime.datetime(2016, 10, 12, 8, 13, 52), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Azure SQL DB - China', '', '', u'Windows Azure Operations Center - China', u'', u'He was migrating his db from asm to arm model)')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24407633L, 4, u'IcM request|HMC P&G| Worker role got  guestheupgrade ', u'700', u'Root Cause', u'4. Completed Investigation', u'User Issue', 'CSS', u'CSS-Shanghai', datetime.datetime(2016, 10, 11, 13, 37, 7, 47000), datetime.datetime(2016, 10, 17, 9, 57, 51), datetime.datetime(2016, 10, 17, 9, 58, 38), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'RDFE - China', u'AZURERTCHINA\\PaaS/Storage', u'PaaS', u'RDFE - China', u'', u'issue diagnosed to be Azure java tool issue,\xa0discuss with Pod TA, who is working on further debugging. agree to resolve')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24411044L, 3, u'Networking | Virtual Networking | [MS-LED]Outbound packet loss to 150.242.59.50:80(SR_2016092051461)', u'900', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 11, 15, 34, 30, 200000), datetime.datetime(2016, 10, 19, 8, 45, 26), datetime.datetime(2016, 10, 19, 20, 10, 3), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u'packet drop', u"PG's had confirm the Pip will fixed customer issue.")
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24413596L, 4, u'MoonCake | WebSites | <failed to migrate a web app to a new service plan through new portal and PowerShell Tool>', u'150', u'Incident', '', u'User Issue', 'CIE', u'CSS-WebApp', datetime.datetime(2016, 10, 11, 16, 46, 12, 17000), datetime.datetime(2016, 10, 12, 14, 17, 30), datetime.datetime(2016, 10, 12, 14, 18, 9), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'WebSites', u'App Service (Web Apps) - China', u'', u'cannot repro,\xa0test subscription agree to close')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24413803L, 4, u'WATS | Networking | S2S VPN |  Loss Package for S2S VPN (SR_2016101153905)', u'70', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 11, 16, 52, 57, 593000), datetime.datetime(2016, 10, 11, 20, 2, 7), datetime.datetime(2016, 10, 11, 20, 2, 23, 480000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet', u'VPN Gateway', u'Finish capture on Role Instance, and send the package to WATS.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24415446L, 3, u"MoonCake | WebSites | <Ibiza portal can't identify site name repetition  > (SR_2016101053819)", u'300', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-WebApp', datetime.datetime(2016, 10, 11, 17, 44, 47, 610000), datetime.datetime(2016, 10, 12, 4, 0, 2), datetime.datetime(2016, 10, 12, 4, 1, 40), u'RESOLVED', None, u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'App Service (Web Apps) - China', u'WINDOWSAZUREWEBSITESCHINA\\WindowsAzureWebsitesServicing', u'WebSites', u'App Service (Web Apps) - China', u'', u'Escalate to Antraes team-->Travis will take a look\nTravis will have a hoxfix.\nBug had been fixed.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24441113L, 3, u'[Mooncake] WA-PaaS| Role in staging slot  stuck in busy for hours ', u'100', u'Incident', '', u'Human Error', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 12, 7, 0, 13, 170000), datetime.datetime(2016, 10, 13, 9, 42, 34), datetime.datetime(2016, 10, 13, 9, 42, 47), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', u'COMPUTEMANAGERMOONCAKE\\ContainerManager', '', u'Windows Azure Operations Center - China', u'', u'You can resolve this ticket as we have found this issue is caused by client code.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24450065L, 3, u'Networking | Virtual Networking | Load Balancer is not working for one VM(SR_2016101254030)', u'320', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 11, 27, 21, 590000), datetime.datetime(2016, 10, 17, 18, 59, 52), datetime.datetime(2016, 10, 17, 19, 0, 30, 193000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'AutoPilot SLB', u'Windows Azure Operations Center - China', u'packet drop', u"load balancer working fine, didn't find any error.")
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24451770L, 3, u'Networking | Virtural Networking | ICM XXXX | Sev 3 | Source discribution mode SLB distribute request from the same source IP to different VMs (SR_2016101154002)', u'320', u'Incident', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 12, 13, 56, 430000), datetime.datetime(2016, 10, 13, 7, 41, 33), datetime.datetime(2016, 10, 19, 11, 5, 59), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u' ', u'Instance affinity is only guaranteed as long as the DIP set does not change. If the DIP set changes, new connections can be routed to different DIPs. This is per design.\nLoad balanced Instance = (Hash calculated over source IP) % (number of instances probed UP)')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24458359L, 3, u'[Mooncake][21V] - [Azul_SR_2016101254130][MSSolve_SR_116101214788444][investigate why exporting database operation is pending]', u'780', u'Incident', u'4. Completed Investigation', u'Network', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 12, 16, 9, 16, 583000), datetime.datetime(2016, 10, 15, 1, 14, 58), datetime.datetime(2016, 10, 15, 1, 16, 10), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\SQLPortal', '', u'Azure SQL DB - China', u'', u'We have got 2 customers reported that export database (China East) operation was pending for a long time, during the issue time, we could repro it. But seems the issue was disappeared around 10/12 12:00 UTC. Now could you please help investigate the issue to provide RCA to customers?--->user may have ill structured data in the database\nA transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.\nThe DacFx service seems return back to a health state after October 12th.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24459040L, 4, u'Need RCA for Virtual Machine hang.', u'190', u'Root Cause', '', u'User Issue', 'other', '', datetime.datetime(2016, 10, 12, 16, 32, 13, 553000), datetime.datetime(2016, 10, 13, 15, 26, 7), datetime.datetime(2016, 10, 13, 15, 26, 39), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\IncidentManager', u'Iaas', u'RDFE - China', u'', u'During issue time wo found no platform change to your VMs but VM CPU is very high. And there are heartbeats between guest and host.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24460934L, 4, u'RCA request for mysql LSI 24419775 on 10/11', u'490', u'Root Cause', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 12, 17, 36, 9, 570000), datetime.datetime(2016, 10, 21, 10, 32, 38), datetime.datetime(2016, 10, 21, 10, 33, 14), u'RESOLVED', None, u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', '', u'MySQL Database on Azure - China', u'', u'RCA delivered')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24462255L, 4, u'NET POD | Sev 4 | Request | Can\'t successfully execute "Stop Diagnostics" for two Vnet on ACIS (SR_2016100153224 & SR_2016101153905)', u'520', u'Incident', u'4. Completed Investigation', u'Platform Change', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 18, 19, 40, 860000), datetime.datetime(2016, 10, 15, 8, 14, 10), datetime.datetime(2016, 10, 15, 8, 14, 34, 937000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Cloudnet - China', '', '', u'Cloudnet - China', u'VPN Gateway', u'The issue is remnant of an earlier issue, where the region of Gateway Tenant were put into wrong format.\nCorrected them now.\nPlease retry, this should have been fixed now.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24463605L, 4, u'pod network  | SR_2016101154011_[MS-LED]SLB can not access ', u'200', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 19, 5, 38, 307000), datetime.datetime(2016, 10, 12, 22, 23, 10), datetime.datetime(2016, 10, 12, 22, 23, 24), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Cloudnet - China', u'', u'The issue was resolved by reset the Kernel parameters.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24471109L, 3, u'WATS  | Sev 3 | [MS-LED]VM is unable to connect(SR_2016101154010)', u'80', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 12, 23, 34, 17, 20000), datetime.datetime(2016, 10, 13, 7, 49, 32), datetime.datetime(2016, 10, 13, 7, 49, 46), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WATS', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'Windows Azure Operations Center - China', u'', u'We have checked the backend the VM\u2019s DIP cannot ping successfully also,Then I checked the VM usage info, this VM\u2019s CPU is up to 100% SINCE 18:00, which matched customer reported.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24497976L, 4, u'[Mooncake][21V] - [Azul_SR_2016101153841][No MSSolve Case][investigate the reason of abnormal export database operation]', u'330', u'Incident', u'4. Completed Investigation', u'Network', 'CIE', u'CSS-SQL', datetime.datetime(2016, 10, 13, 11, 32, 31, 197000), datetime.datetime(2016, 10, 15, 1, 26, 5), datetime.datetime(2016, 10, 15, 1, 26, 52), u'RESOLVED', u'Investigate', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', '', u'Azure SQL DB - China', u'', u'Escalate to SQL team-->Transfer to Managed backup team\nA transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - An existing connection was forcibly closed by the remote host.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24504854L, 4, u'check DDOS Customer of the Sub id and Customer Type ', u'300', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 13, 15, 23, 24, 457000), datetime.datetime(2016, 10, 13, 16, 15, 16), datetime.datetime(2016, 10, 13, 16, 15, 33, 463000), u'RESOLVED', '', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'', u'check DDOS Customer of the Sub id and Customer Type.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24522603L, 3, u'[Mooncake][21V] - [HDInsight][Azul_SR_2016101354352][MSSolve_SR_116101314795554/]Help us to reboot our worknode1 of hdinsight', u'110', None, u'4. Completed Investigation', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 14, 1, 50, 48, 493000), datetime.datetime(2016, 10, 14, 4, 50, 41), datetime.datetime(2016, 10, 14, 4, 52, 8), u'RESOLVED', None, u'HDInsight - China', u'HDINSIGHTCHINA\\LivesiteOnCalls', u'HDInsight - China', '', '', u'HDInsight - China', u'', u'CIE has contacted Hdinsight on-call. WASU help transfer this ticket to PG.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24539032L, 4, u'WASMS | <SR_2016100953630_Customer has bill issue during 10.4--10.10 please help to investigate if the Data transfer billing rule is correct>', u'260', u'Incident', u'2. Engaged', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 10, 14, 9, 39, 5, 90000), datetime.datetime(2016, 10, 18, 11, 3, 21), datetime.datetime(2016, 10, 18, 11, 4, 17), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-BillingPlatform', u'WASU', u'AAD Customer Acquisition and Billing - China', u'', u'Escalate to Billing team--->trying to track down the owner of the data monitor \u2013 it seems like they should own this incident, because the portal/bill are showing the right data as per your analysis below.-->It should be commerce issue instead of Billing portal')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24540431L, 4, u'Networking | Virtual Networking |[RCA] vm networking out data is abnormal from 2016/10/4 to 2016/10/10 CST(SR_2016101153872)', u'90', u'Root Cause', '', u'Duplicate', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 14, 10, 11, 41, 960000), datetime.datetime(2016, 10, 19, 13, 49, 56), datetime.datetime(2016, 10, 19, 13, 50, 25, 840000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'abnormal data out', u'Same ticket as\xa024401415')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24543511L, 3, u'Networking | Virtual Networking | Internal [HMC] Error occures when upload Application Gateway config file(SR_2016101354276)', u'220', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 14, 11, 51, 18, 530000), datetime.datetime(2016, 10, 15, 8, 20, 40), datetime.datetime(2016, 10, 15, 8, 21, 35), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\ApplicationGateway', u'Cloudnet - China', u'CLOUDNETCHINA\\ApplicationGateway', '', u'Cloudnet - China', u'packet drop', u'Escalate to App GW team--->This issue should be fixed with a fleet upgrade (of application gateways) in Mooncake.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24546766L, 3, u'WATS | Networking | VNET | [MS-LED]Unable to update configuration for VNET in new portal (SR_2016101454416)', u'450', u'Incident', u'3. Confirmed Ownership', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 10, 14, 13, 23, 58, 487000), datetime.datetime(2016, 10, 21, 9, 55, 23), datetime.datetime(2016, 10, 21, 9, 55, 41), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'packet drop', u'escalate to Brooklyn team--->The issue is with provisioning of an ER Gateway --> PG suggest to resize GW')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24546809L, 3, u'[Mooncake] WA-TRAFFIC|Failed to add new endpoint', u'820', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-Developer', datetime.datetime(2016, 10, 14, 13, 25, 48, 860000), datetime.datetime(2016, 10, 22, 8, 18, 45), datetime.datetime(2016, 10, 22, 8, 19), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\DNS', u'Azure DNS', u'Cloudnet - China', u'', u'this is a platform bug in the logic to find the authoritative DNS server for customer endpoint and will be fixed in next released.')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:35] INFO (24550739L, 4, u'[POD VMA] WATS | IcM | Sev 4 | [MS-LED]Pls to investigation VM Restart Cause (SR_2016101454392)', u'640', u'Root Cause', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 10, 14, 15, 34, 45, 970000), datetime.datetime(2016, 10, 18, 13, 43, 18), datetime.datetime(2016, 10, 18, 13, 43, 40), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', u'RDOSCHINA\\AzureHost-Sev-3-4', '', u'RDOS - China', u'CRI', u'escalate to CHost team --> this is a bug')
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:24] INFO Insert execl Done!
Wed, 30 Nov 2016 15:39:31:insert_logs.py[line:24] INFO Run done!
Thu, 01 Dec 2016 22:57:57:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 22:58:28:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 22:58:42:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 22:59:05:MS_DB_query.py[line:158] INFO Start Query Db.....
Thu, 01 Dec 2016 22:59:06:MS_DB_query.py[line:192] INFO get_wasu_icm_tickets_user  function issue : (245, "Conversion failed when converting the nvarchar value 'n/a' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")  
Thu, 01 Dec 2016 22:59:06:insert_logs.py[line:24] INFO get_icm_azure_info  function issue : cannot concatenate 'str' and 'bool' objects  
Thu, 01 Dec 2016 22:59:06:insert_logs.py[line:24] INFO Insert execl Done!
Thu, 01 Dec 2016 22:59:06:insert_logs.py[line:24] INFO Run done!
Thu, 01 Dec 2016 23:06:09:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 23:06:30:MS_DB_query.py[line:158] INFO Start Query Db.....
Thu, 01 Dec 2016 23:06:31:MS_DB_query.py[line:192] INFO get_wasu_icm_tickets_user  function issue : (245, "Conversion failed when converting the nvarchar value 'n/a' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")  
Thu, 01 Dec 2016 23:06:31:insert_logs.py[line:24] INFO get_icm_azure_info  function issue : cannot concatenate 'str' and 'bool' objects  
Thu, 01 Dec 2016 23:06:31:insert_logs.py[line:24] INFO Insert execl Done!
Thu, 01 Dec 2016 23:06:31:insert_logs.py[line:24] INFO Run done!
Thu, 01 Dec 2016 23:08:45:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 23:09:00:MS_DB_query.py[line:159] INFO Start Query Db.....
Thu, 01 Dec 2016 23:09:01:MS_DB_query.py[line:193] INFO get_wasu_icm_tickets_user  function issue : (245, "Conversion failed when converting the nvarchar value 'n/a' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")  
Thu, 01 Dec 2016 23:09:01:insert_logs.py[line:24] INFO get_icm_azure_info  function issue : cannot concatenate 'str' and 'bool' objects  
Thu, 01 Dec 2016 23:09:01:insert_logs.py[line:24] INFO Insert execl Done!
Thu, 01 Dec 2016 23:09:01:insert_logs.py[line:24] INFO Run done!
Thu, 01 Dec 2016 23:13:16:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 23:13:16:MS_DB_query.py[line:159] INFO Start Query Db.....
Thu, 01 Dec 2016 23:13:17:MS_DB_query.py[line:194] INFO get_wasu_icm_tickets_user  function issue : (245, "Conversion failed when converting the nvarchar value 'n/a' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")  
Thu, 01 Dec 2016 23:14:50:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 23:14:50:MS_DB_query.py[line:159] INFO Start Query Db.....
Thu, 01 Dec 2016 23:14:51:MS_DB_query.py[line:196] INFO get_wasu_icm_tickets_user  function issue : (245, "Conversion failed when converting the nvarchar value 'n/a' to data type int.DB-Lib error message 20018, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")  
Thu, 01 Dec 2016 23:45:09:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 23:45:09:MS_DB_query.py[line:159] INFO Start Query Db.....
Thu, 01 Dec 2016 23:45:10:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Thu, 01 Dec 2016 23:45:31:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Thu, 01 Dec 2016 23:45:50:MS_DB_query.py[line:159] INFO Start Query Db.....
Thu, 01 Dec 2016 23:45:51:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:24] INFO Db  get_icm_azure_info Done!
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (25959170L, 3, u'Networking | Virtual Networking |  from azure vm to 194.107.0.85 packet loss is very serious_(SR_2016111058265)', u'100', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 11, 9, 30, 20, 943000), datetime.datetime(2016, 11, 14, 22, 5, 1), datetime.datetime(2016, 11, 15, 1, 39, 50), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet loss', u'Need IM help.->There\xa0was\xa0occasional\xa0congestion\xa0in\xa0CT\xa0US network\xa0that\xa0might\xa0cause\xa0some\xa0latency or packet drops.\xa0The\xa0congestion\xa0was\xa0due\xa0to\xa0high\xa0utilization\xa0during\xa0peak\xa0hours.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (25960133L, 4, u"[Mooncake][21V] - [IoTHub][Azul_SR_2016110857821][MSSolve_SR_116111014917569][Android 4.4 can't connect to IoT]", u'1030', u'Root Cause', u'4. Completed Investigation', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 11, 9, 52, 40, 447000), datetime.datetime(2016, 11, 18, 1, 2, 45), datetime.datetime(2016, 11, 22, 11, 7, 56, 360000), u'RESOLVED', None, u'Azure IoT Hub - China', u'AZUREIOTHUBCHINA\\Client', u'Azure IoT Hub - China', u'AZUREIOTHUBCHINA\\IotHub', '', u'Azure IoT Hub - China', u'CSS;Iot;Hub', u'Escalated to Iot Hub team->Need customer to provide the version of Java.-->\xa0you don\u2019t have Root CA and hence you fail on server side validation during\xa0SSL handshake\xa0(Step 3).-->>PG\xa0provided the steps of \xa0adding Root CA is Android cert store')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (25965060L, 4, u'WASMS | <help check if the storage account in the sub is prenium account and the VM is D or DS>', u'300', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 11, 11, 40, 45, 567000), datetime.datetime(2016, 11, 11, 13, 8, 28), datetime.datetime(2016, 11, 11, 13, 8, 42), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'The 2 storage accounts are not premium; those VMs are not D or DS.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (25974514L, 4, u'Please help to collect Non-core services CRI from July to October', u'75', u'Digi', '', u'Diagnostics Data Collection', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 11, 15, 58, 57, 410000), datetime.datetime(2016, 11, 11, 16, 25, 55), datetime.datetime(2016, 11, 11, 16, 26, 23, 833000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'Windows Azure Operations Center - China', u'', u'this is a request from SH CSS Pod Manager to collect Non-core services CRI from July to October.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (25990797L, 4, u'ICP| check subs', u'45', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 11, 23, 30, 54, 10000), datetime.datetime(2016, 11, 12, 0, 23, 11), datetime.datetime(2016, 11, 12, 0, 24, 31, 377000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'CC', u'Windows Azure Operations Center - China', u'', u'check the info of ip.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26002727L, 4, u'ICP| check subs', u'50', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 12, 4, 5, 55, 497000), datetime.datetime(2016, 11, 12, 4, 50, 22), datetime.datetime(2016, 11, 12, 4, 50, 47, 793000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'check SubID')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26022014L, 4, u'IP assist check', u'30', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 12, 12, 26, 11, 930000), datetime.datetime(2016, 11, 12, 12, 42, 33), datetime.datetime(2016, 11, 12, 12, 42, 50, 830000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'done with the request,')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26038996L, 3, u'[Mooncake][21V] - [HDInsight][Azul_SR_2016111258672][MSSolve_SR_116111214928909]falied to query by using Phoenix client connect to Hbase cluster', u'560', u'Incident', u'4. Completed Investigation', u'User Issue', 'Component', u'Component Team', datetime.datetime(2016, 11, 12, 23, 13, 27, 347000), datetime.datetime(2016, 11, 13, 10, 42, 32), datetime.datetime(2016, 11, 17, 1, 40, 36, 900000), u'RESOLVED', None, u'HDInsight - China', u'HDINSIGHTCHINA\\HBase', u'HDInsight - China', u'HDINSIGHTCHINA\\HBase', '', u'HDInsight - China', u'', u'customer issue was gone and Escalate to HBase team-->\xa0VM is overloaded, JVM GC causes HBase operations timeout or slow down.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26043727L, 4, u'ICP | <Title>ip\u534f\u67e5', u'20', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 13, 2, 5, 13, 190000), datetime.datetime(2016, 11, 13, 2, 21, 56), datetime.datetime(2016, 11, 13, 2, 22, 15), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'check subs')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26079316L, 3, u'WA-IaaS|Inaccessible Linux VM|Sev 3 | [MS-LED]Customer VM cannot be accessed by SSH(SR_2016111358710)', u'230', u'Incident', '', u'User Issue', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 13, 23, 19, 40, 910000), datetime.datetime(2016, 11, 14, 0, 30, 7), datetime.datetime(2016, 11, 16, 11, 7, 18, 663000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', u'COMPUTEMANAGERMOONCAKE\\ContainerManager', '', u'Windows Azure Operations Center - China', u'CRI', u'per offline talk, this issue would be caused by customer set ACL rule and WATS is invesitigating with customer about the ping test and cx local network.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26095425L, 2, u'cloud servcice swap failed from staging to production.', u'1140', u'Incident', u'3. Confirmed Ownership', u'LSI', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 14, 2, 57, 20, 903000), datetime.datetime(2016, 11, 14, 9, 46, 19), datetime.datetime(2016, 11, 16, 10, 2, 53, 313000), u'RESOLVED', '', u'Cloudnet - China', u'CLOUDNETCHINA\\RNM', u'RDFE - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'PaaS', u'Cloudnet - China', u'', u"customer's clould service swaped successfully from staging to production at about 9:41, Nov 14 CST")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26127710L, 2, u'PaaS Cloud Service swap failed from staging to production in China East', u'1190', '', '', '', 'other', '', datetime.datetime(2016, 11, 14, 9, 56, 56, 420000), datetime.datetime(2016, 11, 14, 12, 50, 43), datetime.datetime(2016, 11, 30, 3, 41, 7, 940000), u'RESOLVED', '', u'Cloudnet - China', u'CLOUDNETCHINA\\RNM', u'AzureRT', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WALS', u'WALS', u'Cloudnet - China', u'', '')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26128581L, 4, u"WA-IaaS| VM can't start (SR_2016111458721)", u'1100', u'Incident', '', u'LSI', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 14, 10, 24, 2, 930000), datetime.datetime(2016, 11, 14, 14, 4, 55), datetime.datetime(2016, 11, 16, 10, 1, 16), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'Cloudnet - China', u'CRI', u"Confirm with WATS, the 2 customers's issue was mitigated.")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26132599L, 3, u'WASMS | The billed amount display as double tax in account portal.', u'460', u'Incident', u'4. Completed Investigation', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 14, 12, 47, 34, 280000), datetime.datetime(2016, 11, 19, 0, 21, 6), datetime.datetime(2016, 11, 19, 8, 51, 49), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASMS', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\AzureBusinessOperations', u'WASU', u'AAD Customer Acquisition and Billing - China', u'', u'need Tarek help to look at the issue.-->Not platfort issue, commerce side issue-->It seems that this is a\xa0known issue, but they are unable to fix it. We\u2019ve created a work item for next sprint to handle this on our end. http://vstfrd:8080/Azure/RD/_workitems#_a=edit&id=7813782')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26134083L, 3, u"WASMS | <please find why there's premium account in the sub but no premium storage in billing>", u'1180', u'Incident', u'4. Completed Investigation', u'Billing -Invalid Billing', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 14, 13, 47, 15, 563000), datetime.datetime(2016, 11, 23, 11, 16, 56), None, u'MITIGATED', None, u'Xstore - China', u'XSTORECHINA\\Health', u'AAD Customer Acquisition and Billing - China', u'XSTORECHINA\\Health', u'XStore/Health', u'Xstore - China', u'', u'billing issue after 11/21 has been resolved. Xstore/Health team is fixing for bill before mitigation. Per offline talk with CXP\xa0leads Daisy from EA support will help tracking.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26141272L, 4, u'check IP', u'60', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 14, 17, 56, 19, 750000), datetime.datetime(2016, 11, 14, 18, 51, 14), datetime.datetime(2016, 11, 14, 18, 51, 31, 563000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'', u'Have delivered the Sub & Dep info\xa0of the IP\xa0to ICP Support Team')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26146281L, 4, u'WA-IaaS|Inaccessible Windows VM|SR_2016111458930\u2009_\u2009[MS-LED]Cannot start either redeploy VM - VNET in failed status', u'560', u'Incident', '', u'User Issue', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 14, 20, 31, 11, 843000), datetime.datetime(2016, 11, 15, 4, 36, 55), datetime.datetime(2016, 11, 16, 19, 15, 17, 380000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\NRP', '', u'Windows Azure Operations Center - China', u'CRI', u'Customer NSG issue')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26217844L, 1, u'Azure SQL DB Unavailable in China East', u'2000', '', '', '', 'other', '', datetime.datetime(2016, 11, 15, 8, 56, 22, 930000), datetime.datetime(2016, 11, 15, 13, 45, 11), None, u'MITIGATED', '', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Gateway(SterlingDRI)', u'ACS - China', '', '', u'ACS - China', None, '')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26219762L, 4, u'WATS | Podnet | help to check the reason that S2S VPN interrupted(SR_2016111358701)', u'610', u'Root Cause', u'4. Completed Investigation', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 15, 9, 37, 36, 47000), datetime.datetime(2016, 11, 17, 2, 44, 47), datetime.datetime(2016, 11, 17, 2, 45, 7), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN', u'The customer set the error vpn config.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26226487L, 3, u'[Mooncake] WA-TRAFFIC\u201d to \u201cTraffic manager | Not able to access external website through traffic manager with invalid URL error', u'420', u'Incident', u'4. Completed Investigation', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 15, 12, 5, 38, 590000), datetime.datetime(2016, 11, 16, 11, 22, 33), datetime.datetime(2016, 11, 18, 0, 51, 2, 733000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\DNS', u'Traffic Manager', u'Cloudnet - China', u'', u"Need customer check their http server's configuration and make changes with their configuration")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26227609L, 4, u'ICP| check subs', u'30', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 15, 12, 36, 1, 63000), datetime.datetime(2016, 11, 15, 13, 48, 5), datetime.datetime(2016, 11, 15, 13, 48, 42, 330000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'done for this request')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26233477L, 2, u'CIE | SQL server cannot be connect', u'1600', u'Incident', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 11, 15, 14, 52, 47, 833000), datetime.datetime(2016, 11, 15, 14, 56, 31), datetime.datetime(2016, 11, 15, 15, 31, 53), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Azure SQL DB - China', u'AZURESQLDBCHINA\\Availability', '', u'Azure SQL DB - China', u'', u'engaged WALS and PG teams for diagnosing, issue was mitigated by PG and cx confirmed the issue was gone.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26242204L, 3, u"[Mooncake] WA-PaaS| Can't deploy .NET 4.6.1  applicaiton using the latest azure SDK to cloud service", u'240', u'Incident', u'4. Completed Investigation', u'ByDesign', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 15, 17, 49, 46, 700000), datetime.datetime(2016, 11, 16, 10, 21, 1), datetime.datetime(2016, 11, 16, 10, 21, 24, 973000), u'RESOLVED', None, u'RDFE - China', u'AZURERTCHINA\\SDK/PowerShell', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'', u'OsFamily 4 only supports .NET version up to 4.5.2.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26242280L, 4, u'[Mooncake] WA-PaaS|RCA| Ford swap failed issue', u'200', u'Root Cause', u'1. Contacted', u'LSI', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 15, 17, 52, 14, 867000), None, None, u'ACTIVE', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\RNM', u'Cloudnet - China', u'CLOUDNETCHINA\\RNM', '', u'Windows Azure Operations Center - China', u'', u'escalate to RNM')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26244278L, 2, u'[Mooncake][21V] - [Azul_SR_2016111559159][MSSolve_SR_116111514937973]pending when upgrade Azure SQL database from P11 to P15', u'820', u'Incident', u'4. Completed Investigation', u'Platform Bug', 'CIE', u'CSS-SQL', datetime.datetime(2016, 11, 15, 18, 47, 21, 480000), datetime.datetime(2016, 11, 15, 21, 14, 4), datetime.datetime(2016, 11, 26, 13, 39, 12), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBCHINA\\SQLDBPerformance', u'Azure SQL DB', u'AZURESQLDB\\SQLDBResourceIsolation(RG,RgMgr)', '', u'Azure SQL DB - China', u'', u'this deployment (8965315) is complete and we shouldn\u2019t hit pending when upgrade SQL database to P15')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26246527L, 3, u"Network | ExpressRoute | Can't downgrade ER bandwidth ", u'60', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 15, 19, 36, 21, 823000), datetime.datetime(2016, 11, 16, 3, 16, 1), datetime.datetime(2016, 11, 16, 5, 18, 43), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\ExpressRoute', u'Cloudnet - China', u'CLOUDNETCHINA\\ExpressRoute', '', u'Windows Azure Operations Center - China', u'Express Route', u'escalate to ER team')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26246675L, 4, u'[Mooncake][21V] - [RCA][33 cases] | Public RCA for LSI SEV 1 - 26217844', u'820', u'Root Cause', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 11, 15, 19, 38, 47, 870000), datetime.datetime(2016, 11, 18, 9, 48, 35), datetime.datetime(2016, 11, 18, 12, 56, 17), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Gateway(SterlingDRI)', u'Azure SQL DB - China', '', '', u'Windows Azure Operations Center - China', u'RCA', u'transter to SQL tream-->Finish RCA, deliver to CIE')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26253098L, 4, u'ICP | <Please help check customer information>', u'120', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 15, 22, 31, 55, 757000), datetime.datetime(2016, 11, 15, 22, 45, 58), datetime.datetime(2016, 11, 15, 22, 46, 19, 740000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u"check VIP's Sub's info-->Delivered Sub Info for the IPs to IM team")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26256381L, 4, u'Please suspend the deployment of 1RMB trial subscription 82497a38-754f-4987-8c1c-211ac76fca1b below to mitigate CM Beijing congestion', u'60', u'Other', '', u'Update Subscription Setting', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 15, 23, 44, 24, 633000), datetime.datetime(2016, 11, 16, 0, 5, 15), datetime.datetime(2016, 11, 16, 0, 5, 43), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', '', '', u'Cloudnet - China', u'', u'Suspended')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26292617L, 3, u'WATS | Networking | Customers of North America upload/download from Azure VM China is very slow (SR_2016111458795)', u'135', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 16, 11, 19, 59, 303000), datetime.datetime(2016, 11, 21, 17, 28, 41), datetime.datetime(2016, 11, 23, 18, 35, 42, 123000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'', u"Ct's issue.")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26297046L, 4, u'[Mooncake]| Redis Cache| the redis data lose', u'660', u'Root Cause', u'3. Confirmed Ownership', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 16, 13, 37, 45, 477000), datetime.datetime(2016, 11, 17, 8, 44, 7), datetime.datetime(2016, 11, 17, 8, 45, 20), u'RESOLVED', None, u'Redis Cache - China', u'WINDOWSAZURECACHECHINA\\Triage', u'Redis Cache - China', '', u'REDIS Managed Cache Service', u'Redis Cache - China', u'CRI,AzureCache', u'it appears the customer deleted a large number of keys at this time.\xa0 We can see there was a fairly time consuming DEL command executed, which suggests it deleted a very large number of keys:')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26297720L, 3, u'WA-IaaS|Autoscale in classic portal start all instances due to failing to retreive CPU metrics', u'870', u'Incident', u'4. Completed Investigation', u'ByDesign', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 11, 16, 14, 0, 59, 417000), datetime.datetime(2016, 11, 18, 5, 59, 19), datetime.datetime(2016, 11, 19, 0, 37, 9), u'RESOLVED', None, u'Azure Insights - China', u'AZUREINSIGHTSCHINA\\InsightsBackend', u'Azure Insights - China', u'AZUREINSIGHTSCHINA\\Triage', '', u'Windows Azure Operations Center - China', u'CRI', u'the customer has already changed the autoscale setting to max of 2 and default of 2., Unfortuately there is no easy way to update the default instance separately from the max in the Portal.\xa0 It would need to be done via the REST API.Wrt metrics issue, cloud service autoscale relies on a very old legacy pipeline.\xa0 We would recommend that you use a time window of 45 minutes.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26298850L, 4, u'WATS | IcM | Sev 4 | [MS-LED]4 virtual machine in different nodes found the same error(0x00000133)(SR_2016111158540)', u'180', u'Incident', '', u'Platform Bug', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 16, 14, 19, 32, 140000), datetime.datetime(2016, 11, 16, 15, 1, 6), datetime.datetime(2016, 11, 16, 15, 1, 21), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'CRI', u'We have made multiple improvements to target the DPC timeouts and have rolled it out to majority of Public Azure and we have seen significant reduction in the number of bugchecks. The primary change to increase the DPC timeout is part of VFP 17 driver in Nmagent 3.8 payload, this should reduce the number of these instances. These changes have still not hit the moon cake clusters yet as I see all the app clusters are on 3.7. These DPC timeouts will be completely addressed with the rollout of OS144. I will need to followup on the deployment timelines')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26299837L, 3, u'Network | Brooklyn | VPN Gateway Issue (SR_2016111659312_VPN Connection Issue)', u'80', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 16, 14, 56, 45, 740000), datetime.datetime(2016, 11, 22, 11, 18, 2), datetime.datetime(2016, 11, 22, 11, 18, 34, 260000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'VPN Gateway', u"CT's issue.")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26302440L, 3, u'WASMS | customer cannot receive SMS code and the sign up process is blocked at \u201cinput verify code\u201d step', u'10', u'Incident', '', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 16, 16, 21, 36, 857000), datetime.datetime(2016, 11, 16, 16, 47, 30), datetime.datetime(2016, 11, 16, 16, 49, 9, 407000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u"Have told WASMS to find other channel to contact ACN team.WASU don't have the process to escalate ICM ticket to ACN team.")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26315741L, 4, u'suspend 1RMB deployment since CM network bandwidth almost full.', u'240', u'Incident', '', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 16, 23, 28, 41, 650000), datetime.datetime(2016, 11, 17, 0, 52, 20), datetime.datetime(2016, 11, 17, 0, 53, 17, 247000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'', u"due to high traffic, aproved by zhouxiaobin, we suspended 6 deployment which sub 's type belong to 1RMB")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26354613L, 4, u'Could you please help to check customer info', u'80', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 17, 13, 42, 28, 497000), datetime.datetime(2016, 11, 17, 14, 25, 41), datetime.datetime(2016, 11, 17, 14, 26, 15), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\NW/IM', '', u'Windows Azure Operations Center - China', u'', u'check the info of ip.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26357708L, 3, u'Networking | Virtual Networking | VPN creating failed (SR_2016111759506\u2009_\u2009VPN-local network Gateway view  failed\u2009) ', u'550', u'Incident', '', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 17, 15, 25, 16, 810000), datetime.datetime(2016, 11, 21, 19, 42, 6), datetime.datetime(2016, 11, 21, 19, 42, 16), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'packet drop', u'need details from cx\uff1aneed customer to tell the real impact and collect the activety logs')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26358678L, 4, u'Networking | Virtual Networking | Please help troubleshoot vm DNS forwarder log (SR_2016111158564)', u'350', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 17, 16, 2, 55, 23000), datetime.datetime(2016, 11, 22, 11, 9, 41), datetime.datetime(2016, 11, 22, 11, 10, 1, 107000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\DNS', '', u'Cloudnet - China', u'packet drop', u'Customer dns request too fast.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26358831L, 3, u'WASMS | <SR_2016111759592_Suspended Data Transfer by background>', u'20', u'Incident', '', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 17, 16, 7, 20, 717000), datetime.datetime(2016, 11, 17, 16, 51, 19), datetime.datetime(2016, 11, 17, 16, 51, 42), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'Non WASU related')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26360058L, 4, u'Networking | Virtual Networking | RCA-VPN got disconnection from 15:10 to 16:10 of Nov.17th (CST)  (SR_2016111759579)', u'545', u'Incident', u'3. Confirmed Ownership', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 17, 16, 50, 31, 973000), datetime.datetime(2016, 11, 19, 8, 6, 46), datetime.datetime(2016, 11, 19, 8, 8, 49), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', '', u'Cloudnet - China', u'vpn disconnection', u"Tunnel got connected when customer's side dial the connection. When azure initiates, customer's side sends a malformed packets and hence connection fails.\nIf customer wants to know exactly what is malformed we need to work with customer, enable IKE tracking and repro the scenario.")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26367604L, 4, u'Please help to check customer info and suspended the 1RMB deployment with warned subscription', u'520', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 17, 19, 38, 41, 590000), datetime.datetime(2016, 11, 17, 22, 21, 44), datetime.datetime(2016, 11, 17, 22, 22, 1), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\NW/IM', '', u'Windows Azure Operations Center - China', u'', u'Finish checking info and suspending deployments.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26402982L, 3, u'Can\u2019t connect to SHA BE backup cluster on windows Fabric explorer both in sha and bjb delp server', u'870', '', u'2. Engaged', '', 'other', '', datetime.datetime(2016, 11, 18, 11, 15, 10, 780000), datetime.datetime(2016, 11, 24, 16, 47, 2), datetime.datetime(2016, 11, 29, 16, 48, 0, 53000), u'RESOLVED', u'Investigate', u'Power BI - China', u'POWERBICHINA\\PowerBISREs', u'Power BI - China', '', '', u'Power BI - China', u'', u'transfer to service fabric team but need more details about the service fabric cluster.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26407247L, 4, u'[NodeIsolationEvent MC] NodeIsolationEventMC [SH3PrdPFCC01] is unhealthy.', u'30', '', '', '', 'other', '', datetime.datetime(2016, 11, 18, 14, 5, 3, 633000), datetime.datetime(2016, 11, 18, 15, 32, 35), datetime.datetime(2016, 12, 1, 9, 23, 24, 413000), u'RESOLVED', '', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'', '')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26407864L, 4, u'Please help to check customer info', u'120', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 18, 14, 32, 1, 130000), datetime.datetime(2016, 11, 18, 14, 35, 23), datetime.datetime(2016, 11, 18, 14, 35, 50), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\NW/IM', '', u'Windows Azure Operations Center - China', u'', u'check the info of the customer.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26408428L, 4, u'Network | Brooklyn | VPN Gateway Issue (SR_2016111859713)', u'615', u'Root Cause', '', u'Software Update/Maintenance', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 18, 14, 56, 21, 360000), datetime.datetime(2016, 11, 24, 8, 51, 6), datetime.datetime(2016, 11, 24, 8, 51, 42, 463000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', '', u'Cloudnet - China', u'VPN Gateway', u"Platform update. Make the role instance reboot-->the Issue' gone after resetting the VPN Gateway")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26421217L, 4, u'check IP sub/dep and suspend deployment whose subscription is 1RMB and Warned', u'150', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 18, 21, 48, 32, 160000), datetime.datetime(2016, 11, 18, 23, 52, 15), datetime.datetime(2016, 11, 18, 23, 52, 30, 577000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'', u'check and suspend deployment')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26468223L, 2, u'Internet availability degradation observed in multiple clusters from BJB region', u'470', '', '', u'Network', 'other', '', datetime.datetime(2016, 11, 19, 20, 44, 45, 897000), datetime.datetime(2016, 11, 19, 22, 58, 20), None, u'MITIGATED', '', u'Cloudnet - China', u'CLOUDNETCHINA\\CNDRI', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'', u'Issue mitigated after Chinatelecom link up.\nTrace was good during impact time & Towards internet wanetmon was failing intermittently.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26504065L, 2, u'TTA Test @11/20/2016 3:09AM PST', u'120', '', '', '', 'other', '', datetime.datetime(2016, 11, 20, 19, 10, 3, 620000), datetime.datetime(2016, 11, 24, 14, 53, 55), datetime.datetime(2016, 11, 24, 14, 54, 4, 517000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'Windows Azure Operations Center - China', u'test', '')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26527746L, 4, u'WASMS | check ueage of Locally Redundant Disks/Page Blobs and Locally Redundant Block Blobs', u'180', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 21, 11, 48, 16, 710000), datetime.datetime(2016, 11, 21, 15, 1, 2), datetime.datetime(2016, 11, 21, 15, 1, 32), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'check storage usage')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26560457L, 2, u'[Mooncake][21V] - [Azul_SR2016112260146_][MSSolve_SR_:116112114968189][SQL cannot be used after restore]', u'720', u'Incident', u'4. Completed Investigation', u'ByDesign', 'CIE', u'CSS-SQL', datetime.datetime(2016, 11, 22, 6, 37, 29, 487000), datetime.datetime(2016, 11, 22, 7, 49, 27), datetime.datetime(2016, 11, 24, 8, 40, 22, 50000), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\ManagedBackup', u'Azure SQL DB - China', '', '', u'Azure SQL DB - China', u'', u'issue was gone auto, expected took that long. SQL team diagnnosed the reason for\xa0the diff was not used for the restore to be backend feature turned on accidently.\nthe fix will deploy in next week.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26564940L, 4, u'ICP | check IP', u'20', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 22, 8, 29, 24, 670000), datetime.datetime(2016, 11, 22, 8, 47, 31), datetime.datetime(2016, 11, 22, 8, 47, 47), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASMS', u'Windows Azure Operations Center - China', u'', u'check IP')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26572904L, 4, u'WASMS | <SR_2016112159954_Please help to provide the VM shutdown history>', u'330', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 22, 11, 39, 49, 93000), datetime.datetime(2016, 11, 22, 15, 59, 54), datetime.datetime(2016, 11, 22, 16, 26, 43), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'There were one ShutdownRolesOperation for elearning-yt, and three for edu-yungtay, all these operations succeeded.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26578193L, 3, u'Networking | Virtual Networking |IcM 26578193 | VPN packet drop (SR_2016112260178)', u'50', u'Incident', u'1. Contacted', '', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 22, 14, 38, 21, 760000), datetime.datetime(2016, 11, 22, 19, 26, 7), datetime.datetime(2016, 11, 23, 18, 27, 53, 427000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'packet drop', u'Escalated to IM for help')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26579858L, 3, u'Network | Brooklyn | VPN Gateway Issue (SR_2016112260173)', u'150', u'Incident', '', u'Platform Bug', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 22, 15, 35, 0, 710000), datetime.datetime(2016, 11, 24, 8, 36, 53), datetime.datetime(2016, 11, 24, 8, 37, 56, 420000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u"suggest customer reset vpn gateway.-->Customer keeping connect to the backup vpn gateway and results the issue, the issue' gone after resetting the vpn gateway")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26581392L, 3, u'Networking | Virtual Networking | slow network access (SR_2016112260253)', u'30', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 22, 16, 26, 22, 123000), datetime.datetime(2016, 11, 22, 19, 28, 28), datetime.datetime(2016, 11, 23, 18, 30, 21, 883000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'packet drop', u'transfer to IM')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26582425L, 3, u'WASMS | Customer has concerns about  the P15 DB Bills related to SEV2 CRI 26244278', u'480', u'Incident', u'4. Completed Investigation', u'Billing -Valid Billing ', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 22, 17, 2, 35, 687000), datetime.datetime(2016, 11, 26, 13, 31, 22), datetime.datetime(2016, 11, 26, 13, 32, 30), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Billing', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Billing', u'WASU', u'Windows Azure Operations Center - China', u'', u'Related to SEV 2 CRI 26244278, need Ajay help figure out why the customer was charged for P15 usage during 11-17 12:47 CST ~ 11-18 24:00, because he has helped disable the bill during those ours.-they got 23 hours of free P15 - customer -customer want refund all P15 moneny --PG suspend billing for next 15 days')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26584831L, 4, u'test the new tool', u'10', '', '', u'ByDesign', 'Component', u'First Party', datetime.datetime(2016, 11, 22, 17, 46, 58, 100000), datetime.datetime(2016, 11, 22, 17, 48, 19), datetime.datetime(2016, 11, 22, 17, 48, 25, 653000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'Windows Azure Operations Center - China', u'', u'test')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26584972L, 3, u'WATS | Networking | Customers of Taiwan connect from Azure VM China is very slow (SR_2016112260275)', u'55', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 22, 17, 52, 31, 53000), datetime.datetime(2016, 11, 23, 14, 45, 49), datetime.datetime(2016, 11, 24, 10, 42, 14, 980000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'packet drop', u"CT's issue.")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26585508L, 3, u'[Mooncake]| Redis Cache| <Description>', u'300', u'Incident', '', u'User Issue', 'CIE', u'CSS-Developer', datetime.datetime(2016, 11, 22, 18, 8, 29, 850000), datetime.datetime(2016, 11, 22, 18, 13, 6), datetime.datetime(2016, 11, 22, 18, 13, 50, 867000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Redis Cache - China', '', u'REDIS Managed Cache Service', u'Windows Azure Operations Center - China', u'CRI,AzureCache', u'C 1\xa0 hit the max client connection 1000.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26585829L, 3, u'break grass permission request from wats  libing', u'200', '', '', u'LSI', 'other', '', datetime.datetime(2016, 11, 22, 18, 19, 50, 367000), datetime.datetime(2016, 11, 22, 18, 23, 53), datetime.datetime(2016, 11, 22, 18, 24, 43), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', u'COMPUTEMANAGERMOONCAKE\\ContainerManager', '', u'Windows Azure Operations Center - China', u'', u'Temp workaround\uff1a\xa0\n1. \xa0 \xa0 \xa0 Apply \xa0FFE \xa0permission on JIT\n2. \xa0 \xa0 \xa0 Old method: create account on the node.\xa0\n\xa0\nCreateUserAccount /node:05712961-0000-0000-0000-008cfa5056e4 /UserName:***** /Password:***** /container:root /expiration:300\ndeleteuseraccount /node:05712961-0000-0000-0000-008cfa5056e4 /username:***** /Container:root \xa0\nRE: Incident transfer: Sev 2: Id 26581148: Requestor failed to apply JIT access via protal')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26587019L, 3, u'Network | Brooklyn | VPN tunnel  is unstable(SR_2016110957955)', u'40', u'Incident', '', u'Duplicate', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 22, 18, 55, 31, 30000), datetime.datetime(2016, 11, 22, 19, 31, 6), datetime.datetime(2016, 11, 22, 19, 31, 18, 640000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'VPN Gateway', u'duplicate ticket')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26592240L, 4, u'check subscription info for IP', u'30', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 22, 21, 58, 9, 77000), datetime.datetime(2016, 11, 22, 22, 2, 26), datetime.datetime(2016, 11, 22, 22, 2, 34, 850000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'', u'check done')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26618634L, 2, u'WATS | [MS-LED]Automation status is unknown(SR_2016112360391)', u'690', u'Incident', u'4. Completed Investigation', u'LSI', 'other', '', datetime.datetime(2016, 11, 23, 9, 49, 48, 313000), datetime.datetime(2016, 11, 23, 11, 48, 24), datetime.datetime(2016, 11, 23, 11, 49, 24), u'RESOLVED', None, u'Azure Automation - China', u'AZUREAUTOMATIONCHINA\\IncidentManager-China', u'Azure Automation - China', u'AZUREAUTOMATIONCHINA\\Triage', u'WASU', u'Azure Automation - China', u'', u'issue was gone by PG configurate the cert thrumprint.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26619486L, 2, u"Automation status is unknown and also can't creat", u'90', '', '', '', 'other', '', datetime.datetime(2016, 11, 23, 10, 17, 52, 40000), datetime.datetime(2016, 11, 23, 11, 44, 38), datetime.datetime(2016, 11, 23, 11, 47, 27), u'RESOLVED', '', u'Azure Automation - China', u'AZUREAUTOMATIONCHINA\\AzureAutomation-SWE(PG)-China', u'Azure Automation - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'Windows Azure Operations Center - China', u'', '')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26635567L, 3, u'WATS | Podplat | Automation Service display issue(SR_2016112360397)', u'680', u'Incident', u'4. Completed Investigation', u'Platform Change', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 11, 23, 17, 30, 45, 870000), datetime.datetime(2016, 11, 30, 1, 57, 21), datetime.datetime(2016, 11, 30, 1, 58, 31), u'RESOLVED', None, u'Azure Automation - China', u'AZUREAUTOMATIONCHINA\\IncidentManager-China', u'Azure Automation - China', u'AZUREAUTOMATIONCHINA\\IncidentManager', '', u'Azure Automation - China', u'CRI', u'escalate it to automation team.->Wait feedback with customer')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26646772L, 3, u'Network - Outgoing traffic high on Beijing Mobile ISP Link(check ip)', u'350', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 23, 23, 39, 44, 133000), datetime.datetime(2016, 11, 23, 23, 49, 27), datetime.datetime(2016, 11, 23, 23, 49, 41, 843000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'Windows Azure Operations Center - China', u'', u'suspended three deployment-check sub info')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26667671L, 3, u'WASMS | <SR_2016112360600_VM shutdown history>', u'400', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 24, 11, 34, 25, 213000), datetime.datetime(2016, 11, 24, 16, 35, 14), datetime.datetime(2016, 11, 25, 9, 45, 3), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASMS', u'Windows Azure Operations Center - China', '', u'WASU', u'Windows Azure Operations Center - China', u'', u'delivered VM Start/Shutdown operation history & updating history & EnableSubscriptionOperation records & DisableSubscriptionOperation records for the sub to WASMS')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26670477L, 3, u"Networking | Virtual Networking | can't download (SR_2016111859791\u2009_\u2009[HMC]Download is not happening )", u'120', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 24, 13, 29, 8, 520000), datetime.datetime(2016, 11, 30, 10, 48, 39), datetime.datetime(2016, 11, 30, 10, 49, 48), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop', u'Need IM help.-->wats need to close this case.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26670579L, 3, u'WASMS | <please check when and how the VM changed status from 11/5-11/24->', u'200', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 24, 13, 34, 44, 383000), datetime.datetime(2016, 11, 24, 16, 13, 34), datetime.datetime(2016, 11, 24, 16, 14, 4), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'WASU', u'RDFE - China', u'', u'2 cloud services not found and wasu provided history and details.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26672062L, 3, u'Network | Brooklyn | Restart VPN Gateway in  test environment(SR_2016111759579)', u'400', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 24, 14, 25, 33, 973000), datetime.datetime(2016, 11, 25, 7, 36, 19), datetime.datetime(2016, 11, 25, 15, 37, 57, 30000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u'restart vpn gateay done.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26678619L, 4, u'check and Suspend 1RMB warn account Deployment', u'300', '', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 24, 18, 31, 17, 457000), datetime.datetime(2016, 11, 24, 21, 14, 12), datetime.datetime(2016, 11, 24, 21, 14, 35, 667000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'', u'check 12 VIPs subid and depid etc\xa0and suspend two 1RMB warned account.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26688377L, 2, u'Failed to create HDInsight in China East', u'1020', u'Incident', '', u'LSI', 'other', '', datetime.datetime(2016, 11, 25, 0, 44, 50, 727000), datetime.datetime(2016, 11, 25, 2, 43), datetime.datetime(2016, 11, 30, 11, 4, 24, 333000), u'RESOLVED', '', u'HDInsight - China', u'HDINSIGHTCHINA\\LivesiteOnCalls', u'HDInsight - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASU', u'WASU', u'HDInsight - China', u'', u'It due to HDInsight Tenant capacity issue and mitigated by downgraded/released some resources from backend for the tenant.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26703595L, 3, u' IP assist check', u'60', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 25, 11, 31, 17, 627000), datetime.datetime(2016, 11, 25, 11, 52, 46), datetime.datetime(2016, 11, 25, 11, 52, 57), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'21 Vianet', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'check ip')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26704224L, 4, u'check subs', u'80', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 25, 12, 6, 4, 583000), datetime.datetime(2016, 11, 25, 13, 27, 39), datetime.datetime(2016, 11, 25, 13, 27, 55), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'check subs', u'we had done.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26706946L, 3, u'WATS | IcM | Sev 3 | [MS-LED]2VMs can\u2019t connect(SR_2016112560932)', u'320', u'Incident', '', u'User Issue', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 25, 14, 4, 27, 340000), datetime.datetime(2016, 11, 25, 16, 56, 36), datetime.datetime(2016, 11, 25, 16, 57, 27), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'AzureRT', u'AZURERT\\IaaS', u'Iaas', u'AzureRT', u'CRI', u"It's customer vhd issue. Waiting wats feedback.-->vm inside issue")
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26707624L, 4, u'WASMS | pls help check Document DB usage details/logs.', u'600', None, '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 25, 14, 27, 50, 160000), datetime.datetime(2016, 11, 26, 8, 34, 33), datetime.datetime(2016, 11, 26, 8, 34, 48), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASMS', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Experiences', u'PushAgent', u'AAD Customer Acquisition and Billing - China', u'', u'Take 11-16 ~ 11-19 as example: there were 8 collections under that account, each collection is 1000 RUs. As a result,\xa0 the RU is 8000, and the consumed time should be 24*8 hours for one day under the account csmdevmdb.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26711280L, 3, u'WA-IaaS| ASM windows server 2016 zh-cn  cannot activate automatically', u'900', u'Incident', u'2. Engaged', '', 'WATS', u'CSS-IAAS Platform', datetime.datetime(2016, 11, 25, 16, 34, 10, 500000), None, None, u'ACTIVE', u'Investigate', u'RDFE - China', u'AZURERTCHINA\\IaaS', u'Compute Manager - China', u'AZURERTCHINA\\IaaS', u'Iaas', u'Compute Manager - China', u'CRI', u'windows server 2016 zh-cn\xa0 cannot activate automatically --> KMS server fine, PG will check the network packages')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26713211L, 3, u'WATS | Networking | RCA: Local to the Azure network generate huge packet loss (SR_2016112460810 & SR_2016112560898)', u'155', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 25, 17, 45, 6, 780000), datetime.datetime(2016, 11, 26, 2, 32, 38), datetime.datetime(2016, 12, 1, 17, 25, 49, 690000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'packet drop', u'DDos related.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26754828L, 4, u'Networking | Virtual Networking | [RCA] DDoS attack(SR_2016112661073)', u'80', u'Root Cause', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 26, 19, 40, 44, 243000), datetime.datetime(2016, 11, 26, 21, 30, 45), datetime.datetime(2016, 11, 26, 21, 32, 30, 723000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Physical Network', u'Windows Azure Operations Center - China', u'packet drop', u'escalated it to IM team')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26791723L, 3, u'WA-IaaS|Unexpected restart or shutdown_SR_2016112761104', u'360', u'Incident', '', u'Platform Bug', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 27, 21, 50, 0, 443000), datetime.datetime(2016, 11, 27, 23, 59, 10), datetime.datetime(2016, 11, 27, 23, 59, 29, 610000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'', u'Rdagent restart')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26791811L, 4, u'IP assist check', u'300', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 27, 21, 52, 49, 130000), datetime.datetime(2016, 11, 27, 21, 56, 40), datetime.datetime(2016, 11, 27, 21, 57, 40), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'done')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26794459L, 4, u'WA-IaaS|Inaccessible Windows VM|Unexpected reboot_SR_2016112761104', u'750', u'Root Cause', u'4. Completed Investigation', u'Platform Bug', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 11, 27, 23, 52, 48, 577000), datetime.datetime(2016, 11, 30, 9, 10, 13), datetime.datetime(2016, 11, 30, 9, 13, 25), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\NetworkManager', u'Compute Manager - China', u'RDOSCHINA\\AzureHost-Sev-3-4', '', u'RDOS - China', u'', u'Destory container timeout happened twice for different container located in the same node, which would cause node reboot.\xa0The timeout for destroy container is increased from 5 minutes to 20 minutes. It avoids destroy container timeout but cannot completely eliminate it. If the destroy container timeous out even after 20-minute timeout, then the node will still be rebooted.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26807666L, 3, u'Network | Brooklyn | help to  Restart VPN Gateway in test environment(SR_2016111759579)', u'365', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 28, 9, 23, 35, 153000), datetime.datetime(2016, 11, 28, 16, 0, 30), datetime.datetime(2016, 11, 30, 8, 57, 25, 583000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN Gateway', u'we had done.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26810296L, 3, u'check subs', u'30', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 28, 11, 19, 0, 167000), datetime.datetime(2016, 11, 28, 11, 42, 4), datetime.datetime(2016, 11, 28, 11, 42, 24), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'', u'check the info of ip.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26813294L, 3, u'The Subcription was Suspended but still can create MySQL service in classic portal', u'400', u'Incident', '', u'Test Deployment', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 28, 13, 33, 35, 713000), datetime.datetime(2016, 11, 28, 14, 14, 23), datetime.datetime(2016, 11, 28, 14, 15, 42), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', u'ResourceProvider', u'Windows Azure Operations Center - China', u'MySQL', u'Have notified MySQL team.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26814174L, 3, u'suspend Suspend deployment', u'60', u'Digi', '', u'Update Subscription Setting', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 28, 14, 8, 56, 237000), datetime.datetime(2016, 11, 28, 14, 43, 16), datetime.datetime(2016, 11, 28, 14, 43, 42, 920000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'', u'suspend the deployment.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26817481L, 3, u'check subs', u'260', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 28, 16, 11, 19, 87000), datetime.datetime(2016, 11, 28, 17, 41, 47), datetime.datetime(2016, 11, 28, 17, 42, 2), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'done.')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26882715L, 4, u'find illegal host', u'300', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 11, 29, 15, 58, 20, 590000), datetime.datetime(2016, 11, 29, 16, 0, 30), datetime.datetime(2016, 11, 29, 16, 1, 56), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'write a python script to find the illegal host')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26883418L, 4, u'MDS table  SlbHpVmCounterEventbj* didn\u2019t record any data in china north', u'300', '', '', u'Platform Change', 'other', '', datetime.datetime(2016, 11, 29, 16, 8, 55, 30000), datetime.datetime(2016, 11, 29, 16, 12, 34), datetime.datetime(2016, 11, 29, 16, 13, 5, 647000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\SLB', u'Software Load Balancer', u'Windows Azure Operations Center - China', u'', u'The issue was resolved as soon as SLB team uploaded the new storage account keys using the latest MDS Cert.\nCould the Geneva Team investigate the following :\n\n\tIs there an alert when MA starts hitting 401 Error?\n\tWhy did component team have to update keys \xa0in MDS using new cert ? This means that whenever MDS rolls over a new cert, component teams would need to update the mds storage account configuration file.\n\tDuring this time frame, \xa0none of SLB AIMS Rules would have fired. Is there an alert when AIMS Alerts stop working ? J\n\n\n\nI am assigning the following incident to your team for RCA : https://icm.ad.msft.net/imp/IncidentDetails.aspx?id=26857523')
Thu, 01 Dec 2016 23:45:53:insert_logs.py[line:35] INFO (26904826L, 3, u'Networking | Virtual Networking | VPN packet drop (SR_2016112260178)', u'50', u'Incident', u'1. Contacted', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 11, 29, 22, 19, 29, 327000), datetime.datetime(2016, 11, 29, 23, 25, 52), datetime.datetime(2016, 12, 1, 17, 26, 25, 760000), u'RESOLVED', u'Investigate', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'packet drop', u'Escalated to IM for help')
Thu, 01 Dec 2016 23:45:54:insert_logs.py[line:24] INFO Insert execl Done!
Thu, 01 Dec 2016 23:45:54:insert_logs.py[line:24] INFO Run done!
Mon, 12 Dec 2016 14:07:09:MS_DB_query.py[line:37] INFO Connect Warwhouse OK!
Mon, 12 Dec 2016 14:07:30:insert_logs.py[line:38] INFO Input not string/list/dict
Tue, 20 Dec 2016 09:14:35:MS_DB_query.py[line:41] INFO Warwhouse connect issue!
Tue, 20 Dec 2016 09:15:48:MS_DB_query.py[line:41] INFO Warwhouse connect issue!
Tue, 03 Jan 2017 11:01:18:MS_DB_query.py[line:45] INFO Connect Warwhouse OK!
Tue, 03 Jan 2017 11:01:18:MS_DB_query.py[line:167] INFO Start Query Db.....
Tue, 03 Jan 2017 11:01:19:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Tue, 03 Jan 2017 11:06:26:MS_DB_query.py[line:45] INFO Connect Warwhouse OK!
Tue, 03 Jan 2017 11:07:12:MS_DB_query.py[line:167] INFO Start Query Db.....
Tue, 03 Jan 2017 11:07:12:insert_logs.py[line:24] INFO  Query Db get_wasu_icm_tickets_user Done!
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:24] INFO Db  get_icm_azure_info Done!
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (26994424L, 2, u'[WASD2Mcprv2McprCnno1aCR1] MS0008: ManagementService operation timeout for CreateLogicalDatabase more than 10 minutes', u'120', '', u'2. Engaged', None, 'other', '', datetime.datetime(2016, 12, 1, 9, 14, 43, 667000), datetime.datetime(2016, 12, 1, 11, 50), None, u'MITIGATED', '', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Gateway(SterlingDRI)', u'API Management - China', '', '', u'Azure SQL DB - China', None, None)
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (26997391L, 4, u'PSCM replacement for SH3/BM214/PS2', u'850', '', '', '', 'other', '', datetime.datetime(2016, 12, 1, 9, 50, 30, 997000), datetime.datetime(2016, 12, 2, 6, 31, 18), datetime.datetime(2016, 12, 2, 6, 32, 10), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WALS', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WALS', u'WALS', u'Windows Azure Operations Center - China', u'', u'need DCM team help optimaze the script to narrow down the impact nodes only to the PS device not all the rack')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (26999340L, 2, u'[Mooncake][21V] - [Azul_SR_2016120161781|sql Azure failed to retrieve information agaist classical portal', u'900', u'Incident', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 12, 1, 10, 25, 30, 273000), datetime.datetime(2016, 12, 1, 12, 11, 54), datetime.datetime(2016, 12, 1, 12, 12, 36), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Provisioning', u'Azure SQL DB - China', '', '', u'Azure SQL DB - China', u'', u'PG confirmed same causing to LSI\xa0https://icm.ad.msft.net/imp/IncidentDetails.aspx?id=26994424.\xa0Mitigated by enabling EnableAdditionalRelaxedCertificateDistinguishedNameLookup. Provisioning team own RCA.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (26999725L, 2, u'[Mooncake][21V] - [Azul_SR_2016120161781|sql Azure failed to retrieve information agaist classical portal', u'210', '', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 12, 1, 10, 34, 2, 73000), datetime.datetime(2016, 12, 1, 11, 26, 35), datetime.datetime(2016, 12, 1, 12, 8, 43), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Provisioning', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Provisioning', '', u'Azure SQL DB - China', u'', u'PG confirmed same causing to LSI\xa0https://icm.ad.msft.net/imp/IncidentDetails.aspx?id=26994424.\xa0Mitigated by enabling EnableAdditionalRelaxedCertificateDistinguishedNameLookup.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27018181L, 4, u'WASMS | please help to collect recently suspended deployment list', u'75', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 1, 14, 30, 25, 620000), datetime.datetime(2016, 12, 1, 14, 53, 17), datetime.datetime(2016, 12, 1, 14, 53, 47, 447000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'collect recently suspended deployment list')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27018479L, 4, u'WA-IaaS| | MS-LED | VM  Unexpected restart _(SR_2016120161855)', u'460', u'Incident', '', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 12, 1, 14, 39, 16, 120000), datetime.datetime(2016, 12, 1, 15, 39, 37), datetime.datetime(2016, 12, 1, 15, 40, 26), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Compute Manager - China', '', '', u'Windows Azure Operations Center - China', u'CRI', u'Confirmed with WALS, there are some regular PDU Replacement.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27021065L, 4, u'Help IM check Top 5 accounts (By Egress) for MC-SH2PrdStr01A (Real Time) for SEV2[ICM 27019868]', u'60', u'Incident', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 1, 15, 55, 26, 563000), datetime.datetime(2016, 12, 1, 16, 4, 58), datetime.datetime(2016, 12, 1, 16, 5, 17, 893000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Windows Azure Operations Center - China', u'', u'Collect the TOP 5 storage account subscription info for IM.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27025435L, 4, u'Network | Brooklyn | failed to deploy VPN gateway active-active mode in Mooncake ARM and ASM environment.', u'30', u'Incident', '', u'Duplicate', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 1, 18, 3, 1, 173000), datetime.datetime(2016, 12, 2, 10, 11, 49), datetime.datetime(2016, 12, 2, 10, 12, 24, 390000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'VPN Gateway', u'duplicated with\xa027069034')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27069034L, 4, u'Network | Brooklyn | failed to deploy VPN gateway active-active mode in Mooncake ARM and ASM environment.\uff08(SR_2016111759579\uff09', u'660', u'Incident', u'4. Completed Investigation', u'Platform Change', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 2, 9, 42, 34, 480000), datetime.datetime(2016, 12, 5, 14, 10, 40), datetime.datetime(2016, 12, 5, 14, 11, 15, 817000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Cloudnet - China', '', '', u'Cloudnet - China', u'VPN Gateway', u"PG maintained a mapping for features with their respective minimum required gateway sku and we didn\u2019t have such mapping for HighAvailable feature in Mooncake.\xa0They have added it now, need customer to retry the operation again.--> it's fine now.")
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27244130L, 4, u'check subs', u'30', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 5, 10, 12, 29, 103000), datetime.datetime(2016, 12, 5, 10, 30, 24), datetime.datetime(2016, 12, 5, 10, 30, 41, 520000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\CC', u'WASMS', u'Windows Azure Operations Center - China', u'', u'ICP request.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27252291L, 4, u'WASMS | <SR_2016120562293_Update the Account admin and Service admin>', u'70', None, '', u'Update Subscription Setting', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 5, 14, 19, 3, 357000), datetime.datetime(2016, 12, 5, 15, 27, 30), datetime.datetime(2016, 12, 5, 15, 28, 11, 130000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u"Update customer's account admin and service admin.")
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27253016L, 4, u'VPN\u7aef\u53e3\u626b\u63cf\u65e5\u62a5', u'80', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 5, 14, 40, 54, 567000), datetime.datetime(2016, 12, 5, 15, 39, 50), datetime.datetime(2016, 12, 5, 15, 40, 27, 97000), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\CC', u'WASMS', u'Windows Azure Operations Center - China', u'', u'we had done.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27269896L, 4, u'Check VIP info related subscription, in the past month.', u'145', u'Digi', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 5, 21, 20, 57, 860000), datetime.datetime(2016, 12, 5, 22, 0, 55), datetime.datetime(2016, 12, 5, 22, 1, 15), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'Cloudnet - China', '', '', u'Windows Azure Operations Center - China', u'', u'check ip detials with subid')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27311142L, 4, u'Management Portal shows wrong URL for Azure Mooncake Service Dashboard', u'550', u'Incident', u'4. Completed Investigation', u'Platform Change', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 6, 9, 50, 37, 63000), datetime.datetime(2016, 12, 13, 8, 57, 13), datetime.datetime(2016, 12, 14, 10, 18, 14), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\SQLPortal', u'Azure SQL DB', u'AZUREUXCHINA\\AUXPortal', u'Management Portal', u'Azure SQL DB - China', u'', u'SQL team has the fix checked into\xa0next release of Aux portal, will roll out this week.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27315582L, 4, u'Please do subscription owner transfer', u'20', '', '', u'Update Subscription Setting', 'Component', u'Component Team', datetime.datetime(2016, 12, 6, 11, 21, 16, 7000), datetime.datetime(2016, 12, 6, 11, 32, 34), datetime.datetime(2016, 12, 6, 11, 32, 52), u'RESOLVED', '', u'Windows Azure Operations Center - China', u'WASU', u'AAD Customer Acquisition and Billing - China', '', '', u'AAD Customer Acquisition and Billing - China', u'', u'Had mapped to target owner.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27324107L, 4, u'VPN\u7aef\u53e3\u626b\u63cf\u65e5\u62a5', u'1820', '', '', u'Diagnostics Data Collection', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 6, 15, 22, 21, 360000), None, None, u'ACTIVE', '', u'Windows Azure Operations Center - China', u'WASUFirstParty', u'Windows Azure Operations Center - China', u'WINDOWSAZUREOPERATIONSCENTERCHINA\\WASMS', u'WASMS', u'Windows Azure Operations Center - China', u'', u'update 12/31')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27326393L, 3, u'WASMS | customer can not login classic portal ', u'240', u'Incident', u'3. Confirmed Ownership', u'Non WASU Related', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 6, 16, 35, 27, 510000), None, None, u'ACTIVE', '', u'MSODS - China', u'MSODSGallatin\\Triage', u'MSODS - China', u'MSODSGallatin\\Triage', u'WASU', u'MSODS - China', u'', u'CX cannot reset again, Need further assistance from MSODS.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27334199L, 4, u'[Mooncake][21V] - [RCA] for LSI 26994424', u'1120', u'Root Cause', u'4. Completed Investigation', u'LSI', 'CIE', u'CSS-SQL', datetime.datetime(2016, 12, 6, 20, 25, 17, 927000), datetime.datetime(2016, 12, 14, 8, 30, 46), datetime.datetime(2016, 12, 14, 8, 31, 38), u'RESOLVED', None, u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\GeoDR', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\GeoDR', '', u'Azure SQL DB - China', u'', u'Assist with Pochian do the escort to PIR in ACIS,apply JIT and checking format')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27368122L, 3, u'Networking | Virtual Networking | Vm cannot connect  to Guangzhou Fushitong Server(SR_2016120762749)', u'40', u'Incident', None, u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 7, 10, 50, 10, 930000), datetime.datetime(2016, 12, 7, 11, 23, 11), datetime.datetime(2016, 12, 7, 11, 23, 24, 287000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop', u'cx cinformed the issue was gone and agree to close')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27368737L, 3, u'VM created in Classic portal cannot show in Ibiza portal under Virtual Machine (Classic)', u'680', u'Incident', u'4. Completed Investigation', u'Platform Change', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 12, 7, 11, 4, 5, 843000), datetime.datetime(2016, 12, 13, 6, 25, 10), datetime.datetime(2016, 12, 13, 8, 24, 4), u'RESOLVED', None, u'Azure Resource Manager - China', u'AZURERESOURCEMANAGERCHINA\\AzureResourceManager', u'Azure IaaS Experiences (Ibiza) - China', '', '', u'Azure Resource Manager - China', u'', u'[\u200e2016/\u200e12/\u200e13 5:38] Manohar Puttaswamaiah:\nhi, we found the root cause, we will fix it by EOD')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27377716L, 2, u'WASMS | Fail to add new subscription', u'1820', u'Incident', u'4. Completed Investigation', u'LSI', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 7, 14, 41, 3, 213000), datetime.datetime(2016, 12, 7, 17, 48, 18), datetime.datetime(2016, 12, 7, 17, 53, 1), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WASU', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-Experiences', '', u'AAD Customer Acquisition and Billing - China', u'', u'Edit ticket and summary and post brief for the bridge.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27378180L, 2, u'PIA and EA Fail to add new subscription', u'200', '', u'2. Engaged', u'Billing -Valid Billing ', 'WASMS', u'CSS-ASMS', datetime.datetime(2016, 12, 7, 14, 53, 29, 620000), datetime.datetime(2016, 12, 7, 18, 14, 17), None, u'MITIGATED', u'Investigate', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-Experiences', u'AAD Customer Acquisition and Billing - China', u'AADCUSTOMERACQUISITIONANDBILLINGCHINA\\Tier2-Experiences', '', u'Windows Azure Operations Center - China', u'', u'review ticket and collect meeting timeline and other info')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27381738L, 3, u'WATS | Networking | IcM  | Sev 3 | due to unable to parse the domain name, customer cannot access website. (SR_2016120762863)', u'180', u'Incident', '', u'Non WASU Related', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 7, 16, 31, 55, 140000), datetime.datetime(2016, 12, 7, 18, 29, 49), datetime.datetime(2016, 12, 7, 18, 30, 15), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\DNS', '', u'Windows Azure Operations Center - China', u'packet drop', None)
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27447698L, 3, u'Networking | Virtual Networking | image VM  (SR_2016120863088\u2009_\u2009image market create VM IP issue)', u'500', u'Incident', '', u'User Issue', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 8, 17, 56, 57, 313000), datetime.datetime(2016, 12, 9, 17, 21), datetime.datetime(2016, 12, 9, 17, 21, 20), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', '', '', u'Cloudnet - China', u'image market VM', u'need customer confirm the deployment id --> it is BGInfo issue-> wats request to resovle the case')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27450725L, 3, u'Networking | Virtual Networking | VM can not access internet (SR_2016120863180)', u'75', u'Incident', '', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 8, 19, 20, 34, 653000), datetime.datetime(2016, 12, 8, 22, 33, 55), datetime.datetime(2016, 12, 8, 22, 34, 47), u'RESOLVED', u'Triage', u'Windows Azure Operations Center - China', u'WASU', u'Windows Azure Operations Center - China', '', '', u'Windows Azure Operations Center - China', u'packet drop', u'do capture')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27502381L, 4, u'Check DWs\u2019 current status', u'620', u'Incident', u'4. Completed Investigation', u'Diagnostics Data Collection', 'Component', u'First Party', datetime.datetime(2016, 12, 9, 13, 18, 56, 390000), datetime.datetime(2016, 12, 11, 1, 26, 3), datetime.datetime(2016, 12, 11, 1, 26, 20), u'RESOLVED', '', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Datawarehouse', u'Azure SQL DB - China', u'AZURESQLDBMOONCAKE\\Datawarehouse', '', u'Azure SQL DB - China', u'', u'use MDS table check done')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27504501L, 3, u'WATS | Networking | Customer cannot access gsxapi.apple.com:443 from Azure VM (SR_2016120963320)', u'125', u'Incident', u'4. Completed Investigation', u'Network', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 9, 14, 40, 46, 620000), datetime.datetime(2016, 12, 10, 15, 29, 23), datetime.datetime(2016, 12, 15, 8, 44, 3, 40000), u'RESOLVED', None, u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', u'Cloudnet - China', u'CLOUDNETCHINA\\IM/NW', '', u'Cloudnet - China', u'packet drop', u"CT's issue.")
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27508727L, 4, u'MYDBVMSHA-28 crash unexpectedly (IP: 10.0.0.40)', u'500', u'Root Cause', u'4. Completed Investigation', u'Hardware Failure', 'WATS', u'CSS-IAAS Availability', datetime.datetime(2016, 12, 9, 17, 4, 6, 660000), datetime.datetime(2016, 12, 12, 14, 47, 36), datetime.datetime(2016, 12, 12, 14, 48, 9), u'RESOLVED', u'Investigate', u'Azure Hardware Datacenter Manager - China', u'AZUREHARDWAREDATACENTERMANAGERCHINA\\DatacenterPlatform-LowPri', u'MySQL Database on Azure - China', u'MYSQLSERVICE\\Triage', u'InstanceAgent', u'RDOS - China', u'VM Crash', u'Datacenter Platform-Low Pri Team is investigating whether this is hardware issue.\nThe node 05591886-0000-0000-0000-f452141bc7e0 which the VM mydbvmsha-28 located in got unhealthy at 12/9/2016 8:05:14 AM and triggered the self-healing and rebooted, which resulted in the VM reboot as well.')
Tue, 03 Jan 2017 11:07:14:insert_logs.py[line:35] INFO (27509975L, 4, u'Networking | Virtual Networking | customer needs an assist with VPN redundancy test (SR_2016113061686)', u'420', u'Incident', u'1. Contacted', u'Diagnostics Data Collection', 'WATS', u'CSS-Networking', datetime.datetime(2016, 12, 9, 17, 42, 10, 327000), datetime.datetime(2016, 12, 13, 13, 24, 35), datetime.datetime(2016, 12, 14, 10, 9, 47, 93000), u'RESOLVED', None, u'Windows Azure Operations Center - China', u'WATS', u'Cloudnet - China', u'CLOUDNETCHINA\\Brooklyn', u'Brooklyn', u'Cloudnet - China', u'VPN corruption', u'we have done the restart.')
Tue, 03 Jan 2017 11:07:15:insert_logs.py[line:24] INFO Insert execl Done!
Tue, 03 Jan 2017 11:07:15:insert_logs.py[line:24] INFO Run done!
